<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/articulos_familia.php");
	include_once("{$currDir}/articulos_familia_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('articulos_familia');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'articulos_familia';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`articulos_familia`.`id`" => "id",
		"`articulos_familia`.`codigo`" => "codigo",
		"`articulos_familia`.`familia`" => "familia",
		"`articulos_familia`.`proveedor`" => "proveedor",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`articulos_familia`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`articulos_familia`.`id`" => "id",
		"`articulos_familia`.`codigo`" => "codigo",
		"`articulos_familia`.`familia`" => "familia",
		"`articulos_familia`.`proveedor`" => "proveedor",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`articulos_familia`.`id`" => "ID",
		"`articulos_familia`.`codigo`" => "Codigo",
		"`articulos_familia`.`familia`" => "Familia",
		"`articulos_familia`.`proveedor`" => "Proveedor",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`articulos_familia`.`id`" => "id",
		"`articulos_familia`.`codigo`" => "codigo",
		"`articulos_familia`.`familia`" => "familia",
		"`articulos_familia`.`proveedor`" => "proveedor",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`articulos_familia` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'articulos_familia_view.php';
	$x->RedirectAfterInsert = 'articulos_familia_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Articulos familia';
	$x->TableIcon = 'resources/table_icons/cog_add.png';
	$x->PrimaryKey = '`articulos_familia`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Codigo', 'Familia', 'Proveedor', ];
	$x->ColFieldName = ['codigo', 'familia', 'proveedor', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/articulos_familia_templateTV.html';
	$x->SelectedTemplate = 'templates/articulos_familia_templateTVS.html';
	$x->TemplateDV = 'templates/articulos_familia_templateDV.html';
	$x->TemplateDVP = 'templates/articulos_familia_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: articulos_familia_init
	$render = true;
	if(function_exists('articulos_familia_init')) {
		$args = [];
		$render = articulos_familia_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: articulos_familia_header
	$headerCode = '';
	if(function_exists('articulos_familia_header')) {
		$args = [];
		$headerCode = articulos_familia_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: articulos_familia_footer
	$footerCode = '';
	if(function_exists('articulos_familia_footer')) {
		$args = [];
		$footerCode = articulos_familia_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
