<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/biomedicos.php");
	include_once("{$currDir}/biomedicos_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('biomedicos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'biomedicos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`biomedicos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`contactos1`.`identificacion`), CONCAT_WS('',   `contactos1`.`identificacion`), '') /* Id contacto */" => "id_contacto",
		"IF(    CHAR_LENGTH(`contactos1`.`nombre`), CONCAT_WS('',   `contactos1`.`nombre`), '') /* Nombre */" => "nombre",
		"`biomedicos`.`registro_invima`" => "registro_invima",
		"`biomedicos`.`nota`" => "nota",
		"`biomedicos`.`firma`" => "firma",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`biomedicos`.`id`',
		2 => '`contactos1`.`identificacion`',
		3 => '`contactos1`.`nombre`',
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`biomedicos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`contactos1`.`identificacion`), CONCAT_WS('',   `contactos1`.`identificacion`), '') /* Id contacto */" => "id_contacto",
		"IF(    CHAR_LENGTH(`contactos1`.`nombre`), CONCAT_WS('',   `contactos1`.`nombre`), '') /* Nombre */" => "nombre",
		"`biomedicos`.`registro_invima`" => "registro_invima",
		"`biomedicos`.`nota`" => "nota",
		"`biomedicos`.`firma`" => "firma",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`biomedicos`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`contactos1`.`identificacion`), CONCAT_WS('',   `contactos1`.`identificacion`), '') /* Id contacto */" => "Id contacto",
		"IF(    CHAR_LENGTH(`contactos1`.`nombre`), CONCAT_WS('',   `contactos1`.`nombre`), '') /* Nombre */" => "Nombre",
		"`biomedicos`.`registro_invima`" => "No. Registro invima",
		"`biomedicos`.`nota`" => "Nota",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`biomedicos`.`id`" => "id",
		"IF(    CHAR_LENGTH(`contactos1`.`identificacion`), CONCAT_WS('',   `contactos1`.`identificacion`), '') /* Id contacto */" => "id_contacto",
		"IF(    CHAR_LENGTH(`contactos1`.`nombre`), CONCAT_WS('',   `contactos1`.`nombre`), '') /* Nombre */" => "nombre",
		"`biomedicos`.`registro_invima`" => "registro_invima",
		"`biomedicos`.`nota`" => "nota",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['id_contacto' => 'Id contacto', ];

	$x->QueryFrom = "`biomedicos` LEFT JOIN `contactos` as contactos1 ON `contactos1`.`id_contactos`=`biomedicos`.`id_contacto` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'biomedicos_view.php';
	$x->RedirectAfterInsert = 'biomedicos_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Biomedicos';
	$x->TableIcon = 'resources/table_icons/administrator.png';
	$x->PrimaryKey = '`biomedicos`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id contacto', 'Nombre', 'No. Registro invima', 'Nota', 'Firma', ];
	$x->ColFieldName = ['id_contacto', 'nombre', 'registro_invima', 'nota', 'firma', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/biomedicos_templateTV.html';
	$x->SelectedTemplate = 'templates/biomedicos_templateTVS.html';
	$x->TemplateDV = 'templates/biomedicos_templateDV.html';
	$x->TemplateDVP = 'templates/biomedicos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: biomedicos_init
	$render = true;
	if(function_exists('biomedicos_init')) {
		$args = [];
		$render = biomedicos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: biomedicos_header
	$headerCode = '';
	if(function_exists('biomedicos_header')) {
		$args = [];
		$headerCode = biomedicos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: biomedicos_footer
	$footerCode = '';
	if(function_exists('biomedicos_footer')) {
		$args = [];
		$footerCode = biomedicos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
