<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('cantidad_dispomedico');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'nombre_dispo':
			if(!$id) {
				?>
				$j('#serial<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#marca_modelo<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#descripcion<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `compra_dispo`.`id` as 'id', IF(    CHAR_LENGTH(`marca_modelo1`.`img`), CONCAT_WS('',   `marca_modelo1`.`img`), '') as 'foto', `compra_dispo`.`nombre` as 'nombre', `compra_dispo`.`serial` as 'serial', IF(    CHAR_LENGTH(`tipo_dispositivo1`.`tipo_dispositivo`), CONCAT_WS('',   `tipo_dispositivo1`.`tipo_dispositivo`), '') as 'tipo_dispositivo', IF(    CHAR_LENGTH(`marcas1`.`marca`), CONCAT_WS('',   `marcas1`.`marca`), '') as 'marca', IF(    CHAR_LENGTH(`marca_modelo1`.`modelo`), CONCAT_WS('',   `marca_modelo1`.`modelo`), '') as 'modelo', `compra_dispo`.`caracteristicas` as 'caracteristicas', IF(    CHAR_LENGTH(`tipo_estado_dispo1`.`estado_dispo`), CONCAT_WS('',   `tipo_estado_dispo1`.`estado_dispo`), '') as 'estado', IF(    CHAR_LENGTH(`tipo_clasifica_riesgo1`.`clase`) || CHAR_LENGTH(`tipo_clasifica_riesgo1`.`nivel_riesgo`), CONCAT_WS('',   `tipo_clasifica_riesgo1`.`clase`, ' - ', `tipo_clasifica_riesgo1`.`nivel_riesgo`), '') as 'riesgo', `compra_dispo`.`precio` as 'precio', if(`compra_dispo`.`creado`,date_format(`compra_dispo`.`creado`,'%d/%m/%Y %h:%i %p'),'') as 'creado', `compra_dispo`.`creado_por` as 'creado_por' FROM `compra_dispo` LEFT JOIN `tipo_dispositivo` as tipo_dispositivo1 ON `tipo_dispositivo1`.`id_tipodispo`=`compra_dispo`.`tipo_dispositivo` LEFT JOIN `marcas` as marcas1 ON `marcas1`.`id_marca`=`compra_dispo`.`marca` LEFT JOIN `marca_modelo` as marca_modelo1 ON `marca_modelo1`.`id_mmodelo`=`compra_dispo`.`modelo` LEFT JOIN `tipo_estado_dispo` as tipo_estado_dispo1 ON `tipo_estado_dispo1`.`id`=`compra_dispo`.`estado` LEFT JOIN `tipo_clasifica_riesgo` as tipo_clasifica_riesgo1 ON `tipo_clasifica_riesgo1`.`id`=`compra_dispo`.`riesgo`  WHERE `compra_dispo`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#serial<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['serial']))); ?>&nbsp;');
			$j('#marca_modelo<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['marca'].' '.$row['modelo']))); ?>&nbsp;');
			$j('#descripcion<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['caracteristicas'].' '.$row['modelo']))); ?>&nbsp;');
			<?php
			break;


	}

?>