<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/compras.php");
	include_once("{$currDir}/compras_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('compras');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'compras';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`compras`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tipo_compra1`.`tipo_compra`), CONCAT_WS('',   `tipo_compra1`.`tipo_compra`), '') /* Tipo */" => "tipo_compra",
		"if(`compras`.`fecha_compra`,date_format(`compras`.`fecha_compra`,'%d/%m/%Y'),'')" => "fecha_compra",
		"`compras`.`comprador`" => "comprador",
		"`compras`.`resumen`" => "resumen",
		"IF(    CHAR_LENGTH(`tipo_estado_compra1`.`tipo_estado_compra`), CONCAT_WS('',   `tipo_estado_compra1`.`tipo_estado_compra`), '') /* Estado */" => "estado",
		"if(`compras`.`creado`,date_format(`compras`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`compras`.`creado_por`" => "creado_por",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`compras`.`id`',
		2 => '`tipo_compra1`.`tipo_compra`',
		3 => '`compras`.`fecha_compra`',
		4 => 4,
		5 => 5,
		6 => '`tipo_estado_compra1`.`tipo_estado_compra`',
		7 => '`compras`.`creado`',
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`compras`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tipo_compra1`.`tipo_compra`), CONCAT_WS('',   `tipo_compra1`.`tipo_compra`), '') /* Tipo */" => "tipo_compra",
		"if(`compras`.`fecha_compra`,date_format(`compras`.`fecha_compra`,'%d/%m/%Y'),'')" => "fecha_compra",
		"`compras`.`comprador`" => "comprador",
		"`compras`.`resumen`" => "resumen",
		"IF(    CHAR_LENGTH(`tipo_estado_compra1`.`tipo_estado_compra`), CONCAT_WS('',   `tipo_estado_compra1`.`tipo_estado_compra`), '') /* Estado */" => "estado",
		"if(`compras`.`creado`,date_format(`compras`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`compras`.`creado_por`" => "creado_por",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`compras`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`tipo_compra1`.`tipo_compra`), CONCAT_WS('',   `tipo_compra1`.`tipo_compra`), '') /* Tipo */" => "Tipo",
		"`compras`.`fecha_compra`" => "Fecha de transaccion",
		"`compras`.`comprador`" => "Reponsable",
		"`compras`.`resumen`" => "Resumen",
		"IF(    CHAR_LENGTH(`tipo_estado_compra1`.`tipo_estado_compra`), CONCAT_WS('',   `tipo_estado_compra1`.`tipo_estado_compra`), '') /* Estado */" => "Estado",
		"`compras`.`creado`" => "Creado",
		"`compras`.`creado_por`" => "Creado por",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`compras`.`id`" => "id",
		"IF(    CHAR_LENGTH(`tipo_compra1`.`tipo_compra`), CONCAT_WS('',   `tipo_compra1`.`tipo_compra`), '') /* Tipo */" => "tipo_compra",
		"if(`compras`.`fecha_compra`,date_format(`compras`.`fecha_compra`,'%d/%m/%Y'),'')" => "fecha_compra",
		"`compras`.`comprador`" => "comprador",
		"`compras`.`resumen`" => "resumen",
		"IF(    CHAR_LENGTH(`tipo_estado_compra1`.`tipo_estado_compra`), CONCAT_WS('',   `tipo_estado_compra1`.`tipo_estado_compra`), '') /* Estado */" => "estado",
		"if(`compras`.`creado`,date_format(`compras`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`compras`.`creado_por`" => "creado_por",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['tipo_compra' => 'Tipo', 'estado' => 'Estado', ];

	$x->QueryFrom = "`compras` LEFT JOIN `tipo_compra` as tipo_compra1 ON `tipo_compra1`.`id`=`compras`.`tipo_compra` LEFT JOIN `tipo_estado_compra` as tipo_estado_compra1 ON `tipo_estado_compra1`.`id`=`compras`.`estado` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'compras_view.php';
	$x->RedirectAfterInsert = 'compras_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Ingreso / Salida';
	$x->TableIcon = 'resources/table_icons/accept.png';
	$x->PrimaryKey = '`compras`.`id`';
	$x->DefaultSortField = '`compras`.`creado`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Tipo', 'Fecha de transaccion', 'Reponsable', 'Resumen', 'Estado', ];
	$x->ColFieldName = ['tipo_compra', 'fecha_compra', 'comprador', 'resumen', 'estado', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/compras_templateTV.html';
	$x->SelectedTemplate = 'templates/compras_templateTVS.html';
	$x->TemplateDV = 'templates/compras_templateDV.html';
	$x->TemplateDVP = 'templates/compras_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: compras_init
	$render = true;
	if(function_exists('compras_init')) {
		$args = [];
		$render = compras_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: compras_header
	$headerCode = '';
	if(function_exists('compras_header')) {
		$args = [];
		$headerCode = compras_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: compras_footer
	$footerCode = '';
	if(function_exists('compras_footer')) {
		$args = [];
		$footerCode = compras_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
