<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/contactos.php");
	include_once("{$currDir}/contactos_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('contactos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'contactos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`contactos`.`id_contactos`" => "id_contactos",
		"IF(    CHAR_LENGTH(`contactos_tipo_contacto1`.`tipo_contacto`), CONCAT_WS('',   `contactos_tipo_contacto1`.`tipo_contacto`), '') /* Tipo de contacto */" => "tipo_contacto",
		"IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`), '') /* Tipo de ID */" => "tipo_iden",
		"`contactos`.`identificacion`" => "identificacion",
		"`contactos`.`nombre`" => "nombre",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"`contactos`.`telefono`" => "telefono",
		"`contactos`.`direccion`" => "direccion",
		"IF(    CHAR_LENGTH(`tipo_relacion1`.`tipo_relac`), CONCAT_WS('',   `tipo_relacion1`.`tipo_relac`), '') /* Tipo de relacion */" => "tipo_relacion",
		"`contactos`.`nota`" => "nota",
		"if(`contactos`.`reg_creado`,date_format(`contactos`.`reg_creado`,'%d/%m/%Y %h:%i %p'),'')" => "reg_creado",
		"if(`contactos`.`creado`,date_format(`contactos`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`contactos`.`creado_por`" => "creado_por",
		"if(`contactos`.`editado`,date_format(`contactos`.`editado`,'%d/%m/%Y %h:%i %p'),'')" => "editado",
		"`contactos`.`editado_por`" => "editado_por",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`contactos`.`id_contactos`',
		2 => '`contactos_tipo_contacto1`.`tipo_contacto`',
		3 => '`tipo_iden1`.`tipo_iden_abre`',
		4 => 4,
		5 => 5,
		6 => '`ciudades1`.`ciudad`',
		7 => 7,
		8 => 8,
		9 => '`tipo_relacion1`.`tipo_relac`',
		10 => 10,
		11 => '`contactos`.`reg_creado`',
		12 => '`contactos`.`creado`',
		13 => 13,
		14 => '`contactos`.`editado`',
		15 => 15,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`contactos`.`id_contactos`" => "id_contactos",
		"IF(    CHAR_LENGTH(`contactos_tipo_contacto1`.`tipo_contacto`), CONCAT_WS('',   `contactos_tipo_contacto1`.`tipo_contacto`), '') /* Tipo de contacto */" => "tipo_contacto",
		"IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`), '') /* Tipo de ID */" => "tipo_iden",
		"`contactos`.`identificacion`" => "identificacion",
		"`contactos`.`nombre`" => "nombre",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"`contactos`.`telefono`" => "telefono",
		"`contactos`.`direccion`" => "direccion",
		"IF(    CHAR_LENGTH(`tipo_relacion1`.`tipo_relac`), CONCAT_WS('',   `tipo_relacion1`.`tipo_relac`), '') /* Tipo de relacion */" => "tipo_relacion",
		"`contactos`.`nota`" => "nota",
		"if(`contactos`.`reg_creado`,date_format(`contactos`.`reg_creado`,'%d/%m/%Y %h:%i %p'),'')" => "reg_creado",
		"if(`contactos`.`creado`,date_format(`contactos`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`contactos`.`creado_por`" => "creado_por",
		"if(`contactos`.`editado`,date_format(`contactos`.`editado`,'%d/%m/%Y %h:%i %p'),'')" => "editado",
		"`contactos`.`editado_por`" => "editado_por",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`contactos`.`id_contactos`" => "ID",
		"IF(    CHAR_LENGTH(`contactos_tipo_contacto1`.`tipo_contacto`), CONCAT_WS('',   `contactos_tipo_contacto1`.`tipo_contacto`), '') /* Tipo de contacto */" => "Tipo de contacto",
		"IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`), '') /* Tipo de ID */" => "Tipo de ID",
		"`contactos`.`identificacion`" => "No. Identificacion",
		"`contactos`.`nombre`" => "Nombre",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "Ciudad",
		"`contactos`.`telefono`" => "Telefono",
		"`contactos`.`direccion`" => "Direccion",
		"IF(    CHAR_LENGTH(`tipo_relacion1`.`tipo_relac`), CONCAT_WS('',   `tipo_relacion1`.`tipo_relac`), '') /* Tipo de relacion */" => "Tipo de relacion",
		"`contactos`.`nota`" => "Descripci&#243;n",
		"`contactos`.`reg_creado`" => "Reg creado",
		"`contactos`.`creado`" => "Creado",
		"`contactos`.`creado_por`" => "Creado por",
		"`contactos`.`editado`" => "Editado",
		"`contactos`.`editado_por`" => "Editado por",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`contactos`.`id_contactos`" => "id_contactos",
		"IF(    CHAR_LENGTH(`contactos_tipo_contacto1`.`tipo_contacto`), CONCAT_WS('',   `contactos_tipo_contacto1`.`tipo_contacto`), '') /* Tipo de contacto */" => "tipo_contacto",
		"IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`), '') /* Tipo de ID */" => "tipo_iden",
		"`contactos`.`identificacion`" => "identificacion",
		"`contactos`.`nombre`" => "nombre",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"`contactos`.`telefono`" => "telefono",
		"`contactos`.`direccion`" => "direccion",
		"IF(    CHAR_LENGTH(`tipo_relacion1`.`tipo_relac`), CONCAT_WS('',   `tipo_relacion1`.`tipo_relac`), '') /* Tipo de relacion */" => "tipo_relacion",
		"`contactos`.`nota`" => "nota",
		"if(`contactos`.`reg_creado`,date_format(`contactos`.`reg_creado`,'%d/%m/%Y %h:%i %p'),'')" => "reg_creado",
		"if(`contactos`.`creado`,date_format(`contactos`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`contactos`.`creado_por`" => "creado_por",
		"if(`contactos`.`editado`,date_format(`contactos`.`editado`,'%d/%m/%Y %h:%i %p'),'')" => "editado",
		"`contactos`.`editado_por`" => "editado_por",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['tipo_contacto' => 'Tipo de contacto', 'tipo_iden' => 'Tipo de ID', 'ciudad' => 'Ciudad', 'tipo_relacion' => 'Tipo de relacion', ];

	$x->QueryFrom = "`contactos` LEFT JOIN `contactos_tipo_contacto` as contactos_tipo_contacto1 ON `contactos_tipo_contacto1`.`id_tipo_contacto`=`contactos`.`tipo_contacto` LEFT JOIN `tipo_iden` as tipo_iden1 ON `tipo_iden1`.`id_iden`=`contactos`.`tipo_iden` LEFT JOIN `ciudades` as ciudades1 ON `ciudades1`.`id_ciudad`=`contactos`.`ciudad` LEFT JOIN `tipo_relacion` as tipo_relacion1 ON `tipo_relacion1`.`id_tiporelac`=`contactos`.`tipo_relacion` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'contactos_view.php';
	$x->RedirectAfterInsert = 'contactos_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Contactos';
	$x->TableIcon = 'resources/table_icons/ceo.png';
	$x->PrimaryKey = '`contactos`.`id_contactos`';
	$x->DefaultSortField = '`contactos`.`creado`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Tipo de contacto', 'Tipo de ID', 'No. Identificacion', 'Nombre', 'Ciudad', 'Telefono', 'Direccion', 'Tipo de relacion', 'Descripci&#243;n', 'Creado', 'Editado', ];
	$x->ColFieldName = ['tipo_contacto', 'tipo_iden', 'identificacion', 'nombre', 'ciudad', 'telefono', 'direccion', 'tipo_relacion', 'nota', 'creado', 'editado', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/contactos_templateTV.html';
	$x->SelectedTemplate = 'templates/contactos_templateTVS.html';
	$x->TemplateDV = 'templates/contactos_templateDV.html';
	$x->TemplateDVP = 'templates/contactos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: contactos_init
	$render = true;
	if(function_exists('contactos_init')) {
		$args = [];
		$render = contactos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: contactos_header
	$headerCode = '';
	if(function_exists('contactos_header')) {
		$args = [];
		$headerCode = contactos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: contactos_footer
	$footerCode = '';
	if(function_exists('contactos_footer')) {
		$args = [];
		$footerCode = contactos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
