<?php

// Data functions (insert, update, delete, form) for table cronograma_mtto

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function cronograma_mtto_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('cronograma_mtto');
	if(!$arrPerm['insert']) return false;

	$data = [
		'ano' => Request::lookup('id_programa'),
		'codigo' => Request::lookup('codigo', ''),
		'tipo_dispo' => Request::lookup('codigo'),
		'marca' => Request::lookup('marca', ''),
		'modelo' => Request::lookup('codigo'),
		'periodicidad' => Request::lookup('periodicidad', ''),
		'meses' => Request::multipleChoice('meses', ''),
		'biomedico' => Request::val('biomedico', ''),
		'actividades' => Request::val('actividades', ''),
		'creado' => parseCode('<%%creationDateTime%%>', true, true),
		'creado_por' => parseCode('<%%creatorUsername%%>', true),
	];

	if($data['meses'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Meses': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: cronograma_mtto_before_insert
	if(function_exists('cronograma_mtto_before_insert')) {
		$args = [];
		if(!cronograma_mtto_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('cronograma_mtto', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// automatic id_programa if passed as filterer
	if($_REQUEST['filterer_id_programa']) {
		sql("UPDATE `cronograma_mtto` SET `id_programa`='" . makeSafe($_REQUEST['filterer_id_programa']) . "' WHERE `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	update_calc_fields('cronograma_mtto', $recID, calculated_fields()['cronograma_mtto']);

	// hook: cronograma_mtto_after_insert
	if(function_exists('cronograma_mtto_after_insert')) {
		$res = sql("SELECT * FROM `cronograma_mtto` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!cronograma_mtto_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('cronograma_mtto', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) cronograma_mtto_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function cronograma_mtto_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function cronograma_mtto_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('cronograma_mtto', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: cronograma_mtto_before_delete
	if(function_exists('cronograma_mtto_before_delete')) {
		$args = [];
		if(!cronograma_mtto_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `cronograma_mtto` WHERE `id`='{$selected_id}'", $eo);

	// hook: cronograma_mtto_after_delete
	if(function_exists('cronograma_mtto_after_delete')) {
		$args = [];
		cronograma_mtto_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='cronograma_mtto' AND `pkValue`='{$selected_id}'", $eo);
}

function cronograma_mtto_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('cronograma_mtto', $selected_id, 'edit')) return false;

	$data = [
		'ano' => Request::lookup('id_programa'),
		'codigo' => Request::lookup('codigo', ''),
		'tipo_dispo' => Request::lookup('codigo'),
		'marca' => Request::lookup('marca', ''),
		'modelo' => Request::lookup('codigo'),
		'periodicidad' => Request::lookup('periodicidad', ''),
		'meses' => Request::multipleChoice('meses', ''),
		'biomedico' => Request::val('biomedico', ''),
		'actividades' => Request::val('actividades', ''),
	];

	if($data['meses'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Meses': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('cronograma_mtto', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: cronograma_mtto_before_update
	if(function_exists('cronograma_mtto_before_update')) {
		$args = ['old_data' => $old_data];
		if(!cronograma_mtto_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'cronograma_mtto', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="cronograma_mtto_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('cronograma_mtto', $data['selectedID'], calculated_fields()['cronograma_mtto']);

	// hook: cronograma_mtto_after_update
	if(function_exists('cronograma_mtto_after_update')) {
		$res = sql("SELECT * FROM `cronograma_mtto` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!cronograma_mtto_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='cronograma_mtto' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function cronograma_mtto_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('cronograma_mtto');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_id_programa = thisOr($_REQUEST['filterer_id_programa'], '');
	$filterer_codigo = thisOr($_REQUEST['filterer_codigo'], '');
	$filterer_marca = thisOr($_REQUEST['filterer_marca'], '');
	$filterer_periodicidad = thisOr($_REQUEST['filterer_periodicidad'], '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: id_programa
	$combo_id_programa = new DataCombo;
	// combobox: codigo
	$combo_codigo = new DataCombo;
	// combobox: marca
	$combo_marca = new DataCombo;
	// combobox: periodicidad
	$combo_periodicidad = new DataCombo;
	// combobox: meses
	$combo_meses = new Combo;
	$combo_meses->ListType = 3;
	$combo_meses->MultipleSeparator = ', ';
	$combo_meses->ListBoxHeight = 10;
	$combo_meses->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/cronograma_mtto.meses.csv')) {
		$meses_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/cronograma_mtto.meses.csv')));
		$combo_meses->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($meses_data)));
		$combo_meses->ListData = $combo_meses->ListItem;
	} else {
		$combo_meses->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("ENERO;;FEBRERO;;MARZO;;ABRIL;;MAYO;;JUNIO;;JULIO;;AGOSTO;;SEPTIEMBRE;;OCTUBRE;;NOVIEMEMBRE;;DICIEMBRE")));
		$combo_meses->ListData = $combo_meses->ListItem;
	}
	$combo_meses->SelectName = 'meses';
	$combo_meses->AllowNull = false;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='cronograma_mtto' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='cronograma_mtto' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `cronograma_mtto` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'cronograma_mtto_view.php', false);
		}
		$combo_id_programa->SelectedData = $row['id_programa'];
		$combo_codigo->SelectedData = $row['codigo'];
		$combo_marca->SelectedData = $row['marca'];
		$combo_periodicidad->SelectedData = $row['periodicidad'];
		$combo_meses->SelectedData = $row['meses'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_id_programa->SelectedData = $filterer_id_programa;
		$combo_codigo->SelectedData = $filterer_codigo;
		$combo_marca->SelectedData = $filterer_marca;
		$combo_periodicidad->SelectedData = $filterer_periodicidad;
	}
	$combo_id_programa->HTML = '<span id="id_programa-container' . $rnd1 . '"></span><input type="hidden" name="id_programa" id="id_programa' . $rnd1 . '" value="' . html_attr($combo_id_programa->SelectedData) . '">';
	$combo_id_programa->MatchText = '<span id="id_programa-container-readonly' . $rnd1 . '"></span><input type="hidden" name="id_programa" id="id_programa' . $rnd1 . '" value="' . html_attr($combo_id_programa->SelectedData) . '">';
	$combo_codigo->HTML = '<span id="codigo-container' . $rnd1 . '"></span><input type="hidden" name="codigo" id="codigo' . $rnd1 . '" value="' . html_attr($combo_codigo->SelectedData) . '">';
	$combo_codigo->MatchText = '<span id="codigo-container-readonly' . $rnd1 . '"></span><input type="hidden" name="codigo" id="codigo' . $rnd1 . '" value="' . html_attr($combo_codigo->SelectedData) . '">';
	$combo_marca->HTML = '<span id="marca-container' . $rnd1 . '"></span><input type="hidden" name="marca" id="marca' . $rnd1 . '" value="' . html_attr($combo_marca->SelectedData) . '">';
	$combo_marca->MatchText = '<span id="marca-container-readonly' . $rnd1 . '"></span><input type="hidden" name="marca" id="marca' . $rnd1 . '" value="' . html_attr($combo_marca->SelectedData) . '">';
	$combo_periodicidad->HTML = '<span id="periodicidad-container' . $rnd1 . '"></span><input type="hidden" name="periodicidad" id="periodicidad' . $rnd1 . '" value="' . html_attr($combo_periodicidad->SelectedData) . '">';
	$combo_periodicidad->MatchText = '<span id="periodicidad-container-readonly' . $rnd1 . '"></span><input type="hidden" name="periodicidad" id="periodicidad' . $rnd1 . '" value="' . html_attr($combo_periodicidad->SelectedData) . '">';
	$combo_meses->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_id_programa__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['id_programa'] : htmlspecialchars($filterer_id_programa, ENT_QUOTES)); ?>"};
		AppGini.current_codigo__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['codigo'] : htmlspecialchars($filterer_codigo, ENT_QUOTES)); ?>"};
		AppGini.current_marca__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['marca'] : htmlspecialchars($filterer_marca, ENT_QUOTES)); ?>"};
		AppGini.current_periodicidad__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['periodicidad'] : htmlspecialchars($filterer_periodicidad, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(id_programa_reload__RAND__) == 'function') id_programa_reload__RAND__();
				if(typeof(codigo_reload__RAND__) == 'function') codigo_reload__RAND__();
				if(typeof(marca_reload__RAND__) == 'function') marca_reload__RAND__();
				if(typeof(periodicidad_reload__RAND__) == 'function') periodicidad_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function id_programa_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#id_programa-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_id_programa__RAND__.value, t: 'cronograma_mtto', f: 'id_programa' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="id_programa"]').val(resp.results[0].id);
							$j('[id=id_programa-container-readonly__RAND__]').html('<span id="id_programa-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=programa_mtto_view_parent]').hide(); } else { $j('.btn[id=programa_mtto_view_parent]').show(); }


							if(typeof(id_programa_update_autofills__RAND__) == 'function') id_programa_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'cronograma_mtto', f: 'id_programa' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_id_programa__RAND__.value = e.added.id;
				AppGini.current_id_programa__RAND__.text = e.added.text;
				$j('[name="id_programa"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=programa_mtto_view_parent]').hide(); } else { $j('.btn[id=programa_mtto_view_parent]').show(); }


				if(typeof(id_programa_update_autofills__RAND__) == 'function') id_programa_update_autofills__RAND__();
			});

			if(!$j("#id_programa-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_id_programa__RAND__.value, t: 'cronograma_mtto', f: 'id_programa' },
					success: function(resp) {
						$j('[name="id_programa"]').val(resp.results[0].id);
						$j('[id=id_programa-container-readonly__RAND__]').html('<span id="id_programa-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=programa_mtto_view_parent]').hide(); } else { $j('.btn[id=programa_mtto_view_parent]').show(); }

						if(typeof(id_programa_update_autofills__RAND__) == 'function') id_programa_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_id_programa__RAND__.value, t: 'cronograma_mtto', f: 'id_programa' },
				success: function(resp) {
					$j('[id=id_programa-container__RAND__], [id=id_programa-container-readonly__RAND__]').html('<span id="id_programa-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=programa_mtto_view_parent]').hide(); } else { $j('.btn[id=programa_mtto_view_parent]').show(); }

					if(typeof(id_programa_update_autofills__RAND__) == 'function') id_programa_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function codigo_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#codigo-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_codigo__RAND__.value, t: 'cronograma_mtto', f: 'codigo' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="codigo"]').val(resp.results[0].id);
							$j('[id=codigo-container-readonly__RAND__]').html('<span id="codigo-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=dispositivos_view_parent]').hide(); } else { $j('.btn[id=dispositivos_view_parent]').show(); }


							if(typeof(codigo_update_autofills__RAND__) == 'function') codigo_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'cronograma_mtto', f: 'codigo' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_codigo__RAND__.value = e.added.id;
				AppGini.current_codigo__RAND__.text = e.added.text;
				$j('[name="codigo"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=dispositivos_view_parent]').hide(); } else { $j('.btn[id=dispositivos_view_parent]').show(); }


				if(typeof(codigo_update_autofills__RAND__) == 'function') codigo_update_autofills__RAND__();
			});

			if(!$j("#codigo-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_codigo__RAND__.value, t: 'cronograma_mtto', f: 'codigo' },
					success: function(resp) {
						$j('[name="codigo"]').val(resp.results[0].id);
						$j('[id=codigo-container-readonly__RAND__]').html('<span id="codigo-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=dispositivos_view_parent]').hide(); } else { $j('.btn[id=dispositivos_view_parent]').show(); }

						if(typeof(codigo_update_autofills__RAND__) == 'function') codigo_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_codigo__RAND__.value, t: 'cronograma_mtto', f: 'codigo' },
				success: function(resp) {
					$j('[id=codigo-container__RAND__], [id=codigo-container-readonly__RAND__]').html('<span id="codigo-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=dispositivos_view_parent]').hide(); } else { $j('.btn[id=dispositivos_view_parent]').show(); }

					if(typeof(codigo_update_autofills__RAND__) == 'function') codigo_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function marca_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#marca-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_marca__RAND__.value, t: 'cronograma_mtto', f: 'marca' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="marca"]').val(resp.results[0].id);
							$j('[id=marca-container-readonly__RAND__]').html('<span id="marca-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=marcas_view_parent]').hide(); } else { $j('.btn[id=marcas_view_parent]').show(); }


							if(typeof(marca_update_autofills__RAND__) == 'function') marca_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'cronograma_mtto', f: 'marca' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_marca__RAND__.value = e.added.id;
				AppGini.current_marca__RAND__.text = e.added.text;
				$j('[name="marca"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=marcas_view_parent]').hide(); } else { $j('.btn[id=marcas_view_parent]').show(); }


				if(typeof(marca_update_autofills__RAND__) == 'function') marca_update_autofills__RAND__();
			});

			if(!$j("#marca-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_marca__RAND__.value, t: 'cronograma_mtto', f: 'marca' },
					success: function(resp) {
						$j('[name="marca"]').val(resp.results[0].id);
						$j('[id=marca-container-readonly__RAND__]').html('<span id="marca-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=marcas_view_parent]').hide(); } else { $j('.btn[id=marcas_view_parent]').show(); }

						if(typeof(marca_update_autofills__RAND__) == 'function') marca_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_marca__RAND__.value, t: 'cronograma_mtto', f: 'marca' },
				success: function(resp) {
					$j('[id=marca-container__RAND__], [id=marca-container-readonly__RAND__]').html('<span id="marca-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=marcas_view_parent]').hide(); } else { $j('.btn[id=marcas_view_parent]').show(); }

					if(typeof(marca_update_autofills__RAND__) == 'function') marca_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function periodicidad_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#periodicidad-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_periodicidad__RAND__.value, t: 'cronograma_mtto', f: 'periodicidad' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="periodicidad"]').val(resp.results[0].id);
							$j('[id=periodicidad-container-readonly__RAND__]').html('<span id="periodicidad-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=tipo_periodicidad_view_parent]').hide(); } else { $j('.btn[id=tipo_periodicidad_view_parent]').show(); }


							if(typeof(periodicidad_update_autofills__RAND__) == 'function') periodicidad_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'cronograma_mtto', f: 'periodicidad' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_periodicidad__RAND__.value = e.added.id;
				AppGini.current_periodicidad__RAND__.text = e.added.text;
				$j('[name="periodicidad"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=tipo_periodicidad_view_parent]').hide(); } else { $j('.btn[id=tipo_periodicidad_view_parent]').show(); }


				if(typeof(periodicidad_update_autofills__RAND__) == 'function') periodicidad_update_autofills__RAND__();
			});

			if(!$j("#periodicidad-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_periodicidad__RAND__.value, t: 'cronograma_mtto', f: 'periodicidad' },
					success: function(resp) {
						$j('[name="periodicidad"]').val(resp.results[0].id);
						$j('[id=periodicidad-container-readonly__RAND__]').html('<span id="periodicidad-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=tipo_periodicidad_view_parent]').hide(); } else { $j('.btn[id=tipo_periodicidad_view_parent]').show(); }

						if(typeof(periodicidad_update_autofills__RAND__) == 'function') periodicidad_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_periodicidad__RAND__.value, t: 'cronograma_mtto', f: 'periodicidad' },
				success: function(resp) {
					$j('[id=periodicidad-container__RAND__], [id=periodicidad-container-readonly__RAND__]').html('<span id="periodicidad-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=tipo_periodicidad_view_parent]').hide(); } else { $j('.btn[id=tipo_periodicidad_view_parent]').show(); }

					if(typeof(periodicidad_update_autofills__RAND__) == 'function') periodicidad_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/cronograma_mtto_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/cronograma_mtto_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Cronograma mtto details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return cronograma_mtto_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return cronograma_mtto_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return cronograma_mtto_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#codigo').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#codigo_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#marca').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#marca_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#periodicidad').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#periodicidad_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#meses').replaceWith('<div class=\"form-control-static\" id=\"meses\">' + (jQuery('#meses').val() || '') + '</div>'); jQuery('#meses-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#s2id_meses').remove();\n";
		$jsReadOnly .= "\tjQuery('#biomedico').replaceWith('<div class=\"form-control-static\" id=\"biomedico\">' + (jQuery('#biomedico').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#actividades').replaceWith('<div class=\"form-control-static\" id=\"actividades\">' + (jQuery('#actividades').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(id_programa)%%>', $combo_id_programa->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(id_programa)%%>', $combo_id_programa->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(id_programa)%%>', urlencode($combo_id_programa->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(codigo)%%>', $combo_codigo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(codigo)%%>', $combo_codigo->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(codigo)%%>', urlencode($combo_codigo->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(marca)%%>', $combo_marca->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(marca)%%>', $combo_marca->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(marca)%%>', urlencode($combo_marca->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(periodicidad)%%>', $combo_periodicidad->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(periodicidad)%%>', $combo_periodicidad->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(periodicidad)%%>', urlencode($combo_periodicidad->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(meses)%%>', $combo_meses->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(meses)%%>', $combo_meses->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('id_programa' => array('programa_mtto', 'Tipo dispo'), 'codigo' => array('dispositivos', 'codigo del dispositivo'), 'marca' => array('marcas', 'Marca'), 'periodicidad' => array('tipo_periodicidad', 'Periodicidad'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(id_programa)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(codigo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(marca)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(periodicidad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(meses)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(biomedico)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(actividades)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(creado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(creado_por)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_programa)%%>', safe_html($urow['id_programa']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_programa)%%>', urlencode($urow['id_programa']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(codigo)%%>', safe_html($urow['codigo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(codigo)%%>', html_attr($row['codigo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(codigo)%%>', urlencode($urow['codigo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(marca)%%>', safe_html($urow['marca']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(marca)%%>', html_attr($row['marca']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(marca)%%>', urlencode($urow['marca']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(periodicidad)%%>', safe_html($urow['periodicidad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(periodicidad)%%>', html_attr($row['periodicidad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(periodicidad)%%>', urlencode($urow['periodicidad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(meses)%%>', safe_html($urow['meses']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(meses)%%>', html_attr($row['meses']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(meses)%%>', urlencode($urow['meses']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(biomedico)%%>', safe_html($urow['biomedico']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(biomedico)%%>', html_attr($row['biomedico']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(biomedico)%%>', urlencode($urow['biomedico']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(actividades)%%>', safe_html($urow['actividades']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(actividades)%%>', html_attr($row['actividades']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(actividades)%%>', urlencode($urow['actividades']), $templateCode);
		$templateCode = str_replace('<%%VALUE(creado)%%>', app_datetime($row['creado'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creado)%%>', urlencode(app_datetime($urow['creado'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(creado_por)%%>', safe_html($urow['creado_por']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creado_por)%%>', urlencode($urow['creado_por']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(id_programa)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id_programa)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(codigo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(codigo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(marca)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(marca)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(periodicidad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(periodicidad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(meses)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(meses)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(biomedico)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(biomedico)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(actividades)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(actividades)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(creado)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creado)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(creado_por)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creado_por)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tid_programa_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'cronograma_mtto_autofill.php?rnd1=$rnd1&mfk=id_programa&id=' + encodeURIComponent('".addslashes($row['id_programa'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'cronograma_mtto_autofill.php?rnd1=$rnd1&mfk=id_programa&id=' + encodeURIComponent(AppGini.current_id_programa{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#id_programa$rnd1').prop('disabled', true); \$j('#id_programaLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#id_programa$rnd1').prop('disabled', false); " : "\$j('#id_programa$rnd1').prop('disabled', true); ")."\$j('#id_programaLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#id_programa_caption').length) \$j('#id_programa_caption').click(function() { id_programa_update_autofills$rnd1(); });\n";

	$templateCode .= "\tcodigo_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'cronograma_mtto_autofill.php?rnd1=$rnd1&mfk=codigo&id=' + encodeURIComponent('".addslashes($row['codigo'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'cronograma_mtto_autofill.php?rnd1=$rnd1&mfk=codigo&id=' + encodeURIComponent(AppGini.current_codigo{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#codigo$rnd1').prop('disabled', true); \$j('#codigoLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#codigo$rnd1').prop('disabled', false); " : "\$j('#codigo$rnd1').prop('disabled', true); ")."\$j('#codigoLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#codigo_caption').length) \$j('#codigo_caption').click(function() { codigo_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	if( $_REQUEST['FilterField'][1]=='2' && $_REQUEST['FilterOperator'][1]=='<=>') {
		$templateCode.="\n<input type=hidden name=id_programa value=\"" . html_attr($_REQUEST['FilterValue'][1]) . "\">\n";
	}

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('cronograma_mtto');
	if($selected_id) {
		$jdata = get_joined_record('cronograma_mtto', $selected_id);
		if($jdata === false) $jdata = get_defaults('cronograma_mtto');
		$rdata = $row;
	}
	$templateCode .= loadView('cronograma_mtto-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: cronograma_mtto_dv
	if(function_exists('cronograma_mtto_dv')) {
		$args=[];
		cronograma_mtto_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}