<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/genera_documentos.php");
	include_once("{$currDir}/genera_documentos_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('genera_documentos');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'genera_documentos';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`genera_documentos`.`id`" => "id",
		"`genera_documentos`.`tipo_documento_entrega`" => "tipo_documento_entrega",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"if(`genera_documentos`.`fecha`,date_format(`genera_documentos`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"IF(    CHAR_LENGTH(`unidades1`.`nombre`) || CHAR_LENGTH(`unidades1`.`abreviado`), CONCAT_WS('',   `unidades1`.`nombre`, ' - ', `unidades1`.`abreviado`), '') /* Entidad */" => "entidad",
		"`genera_documentos`.`referencia`" => "referencia",
		"`genera_documentos`.`descripcion`" => "descripcion",
		"`genera_documentos`.`conslusion`" => "conslusion",
		"if(`genera_documentos`.`creado`,date_format(`genera_documentos`.`creado`,'%d/%m/%Y'),'')" => "creado",
		"`genera_documentos`.`creado_por`" => "creado_por",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`genera_documentos`.`id`',
		2 => 2,
		3 => '`ciudades1`.`ciudad`',
		4 => '`genera_documentos`.`fecha`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`genera_documentos`.`creado`',
		10 => 10,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`genera_documentos`.`id`" => "id",
		"`genera_documentos`.`tipo_documento_entrega`" => "tipo_documento_entrega",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"if(`genera_documentos`.`fecha`,date_format(`genera_documentos`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"IF(    CHAR_LENGTH(`unidades1`.`nombre`) || CHAR_LENGTH(`unidades1`.`abreviado`), CONCAT_WS('',   `unidades1`.`nombre`, ' - ', `unidades1`.`abreviado`), '') /* Entidad */" => "entidad",
		"`genera_documentos`.`referencia`" => "referencia",
		"`genera_documentos`.`descripcion`" => "descripcion",
		"`genera_documentos`.`conslusion`" => "conslusion",
		"if(`genera_documentos`.`creado`,date_format(`genera_documentos`.`creado`,'%d/%m/%Y'),'')" => "creado",
		"`genera_documentos`.`creado_por`" => "creado_por",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`genera_documentos`.`id`" => "ID",
		"`genera_documentos`.`tipo_documento_entrega`" => "Tipo de documento",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "Ciudad",
		"`genera_documentos`.`fecha`" => "Fecha",
		"IF(    CHAR_LENGTH(`unidades1`.`nombre`) || CHAR_LENGTH(`unidades1`.`abreviado`), CONCAT_WS('',   `unidades1`.`nombre`, ' - ', `unidades1`.`abreviado`), '') /* Entidad */" => "Entidad",
		"`genera_documentos`.`referencia`" => "Referencia",
		"`genera_documentos`.`descripcion`" => "Descripcion",
		"`genera_documentos`.`conslusion`" => "Conslusion",
		"`genera_documentos`.`creado`" => "Creado",
		"`genera_documentos`.`creado_por`" => "Creado por",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`genera_documentos`.`id`" => "id",
		"`genera_documentos`.`tipo_documento_entrega`" => "tipo_documento_entrega",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"if(`genera_documentos`.`fecha`,date_format(`genera_documentos`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"IF(    CHAR_LENGTH(`unidades1`.`nombre`) || CHAR_LENGTH(`unidades1`.`abreviado`), CONCAT_WS('',   `unidades1`.`nombre`, ' - ', `unidades1`.`abreviado`), '') /* Entidad */" => "entidad",
		"`genera_documentos`.`referencia`" => "referencia",
		"`genera_documentos`.`descripcion`" => "descripcion",
		"`genera_documentos`.`conslusion`" => "conslusion",
		"if(`genera_documentos`.`creado`,date_format(`genera_documentos`.`creado`,'%d/%m/%Y'),'')" => "creado",
		"`genera_documentos`.`creado_por`" => "creado_por",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['ciudad' => 'Ciudad', 'entidad' => 'Entidad', ];

	$x->QueryFrom = "`genera_documentos` LEFT JOIN `ciudades` as ciudades1 ON `ciudades1`.`id_ciudad`=`genera_documentos`.`ciudad` LEFT JOIN `unidades` as unidades1 ON `unidades1`.`id_unidades`=`genera_documentos`.`entidad` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'genera_documentos_view.php';
	$x->RedirectAfterInsert = 'genera_documentos_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Genera documentos';
	$x->TableIcon = 'resources/table_icons/cog_add.png';
	$x->PrimaryKey = '`genera_documentos`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Tipo de documento', 'Ciudad', 'Fecha', 'Entidad', 'Referencia', 'Descripcion', 'Conslusion', 'Creado', 'Creado por', ];
	$x->ColFieldName = ['tipo_documento_entrega', 'ciudad', 'fecha', 'entidad', 'referencia', 'descripcion', 'conslusion', 'creado', 'creado_por', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/genera_documentos_templateTV.html';
	$x->SelectedTemplate = 'templates/genera_documentos_templateTVS.html';
	$x->TemplateDV = 'templates/genera_documentos_templateDV.html';
	$x->TemplateDVP = 'templates/genera_documentos_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: genera_documentos_init
	$render = true;
	if(function_exists('genera_documentos_init')) {
		$args = [];
		$render = genera_documentos_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: genera_documentos_header
	$headerCode = '';
	if(function_exists('genera_documentos_header')) {
		$args = [];
		$headerCode = genera_documentos_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: genera_documentos_footer
	$footerCode = '';
	if(function_exists('genera_documentos_footer')) {
		$args = [];
		$footerCode = genera_documentos_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
