<?php

// Data functions (insert, update, delete, form) for table hojadevida

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function hojadevida_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('hojadevida');
	if(!$arrPerm['insert']) return false;

	$data = [
		'dispo_codigo' => Request::lookup('dispo_codigo', ''),
		'dispo_serial' => Request::lookup('dispo_codigo'),
		'hardware' => Request::val('hardware', ''),
		'software' => Request::val('software', ''),
		'carga' => Request::fileUpload('carga', [
			'maxSize' => 5120000,
			'types' => 'doc|docx|pdf|jpg|jpge|bpm|png',
			'noRename' => true,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!isset($_REQUEST['SelectedID'])) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('hojadevida', 'carga', $_REQUEST['SelectedID']);
			},
		]),
		'creado' => parseCode('<%%creationDateTime%%>', true, true),
		'creado_por' => parseCode('<%%creatorUsername%%>', true),
	];

	if($data['dispo_codigo'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Codigo': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: hojadevida_before_insert
	if(function_exists('hojadevida_before_insert')) {
		$args = [];
		if(!hojadevida_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('hojadevida', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('hojadevida', $recID, calculated_fields()['hojadevida']);

	// hook: hojadevida_after_insert
	if(function_exists('hojadevida_after_insert')) {
		$res = sql("SELECT * FROM `hojadevida` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!hojadevida_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('hojadevida', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) hojadevida_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function hojadevida_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function hojadevida_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('hojadevida', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: hojadevida_before_delete
	if(function_exists('hojadevida_before_delete')) {
		$args = [];
		if(!hojadevida_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// delete file stored in the 'carga' field
	$res = sql("SELECT `carga` FROM `hojadevida` WHERE `id`='{$selected_id}'", $eo);
	if($row = @db_fetch_row($res)) {
		if($row[0] != '') {
			@unlink(getUploadDir('') . $row[0]);
		}
	}

	sql("DELETE FROM `hojadevida` WHERE `id`='{$selected_id}'", $eo);

	// hook: hojadevida_after_delete
	if(function_exists('hojadevida_after_delete')) {
		$args = [];
		hojadevida_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='hojadevida' AND `pkValue`='{$selected_id}'", $eo);
}

function hojadevida_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('hojadevida', $selected_id, 'edit')) return false;

	$data = [
		'dispo_codigo' => Request::lookup('dispo_codigo', ''),
		'dispo_serial' => Request::lookup('dispo_codigo'),
		'hardware' => Request::val('hardware', ''),
		'software' => Request::val('software', ''),
		'carga' => Request::fileUpload('carga', [
			'maxSize' => 5120000,
			'types' => 'doc|docx|pdf|jpg|jpge|bpm|png',
			'noRename' => true,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnSuccess' => true,
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// delete old file from server
				$oldFile = existing_value('hojadevida', 'carga', $selected_id);
				if(!$oldFile) return;

				@unlink(getUploadDir('') . $oldFile);
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('hojadevida', 'carga', $selected_id);
			},
		]),
		'editado' => parseCode('<%%editingDateTime%%>', false, true),
		'editado_por' => parseCode('<%%editorUsername%%>', false),
	];

	if($data['dispo_codigo'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Codigo': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('hojadevida', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: hojadevida_before_update
	if(function_exists('hojadevida_before_update')) {
		$args = ['old_data' => $old_data];
		if(!hojadevida_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'hojadevida', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="hojadevida_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('hojadevida', $data['selectedID'], calculated_fields()['hojadevida']);

	// hook: hojadevida_after_update
	if(function_exists('hojadevida_after_update')) {
		$res = sql("SELECT * FROM `hojadevida` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!hojadevida_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='hojadevida' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function hojadevida_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('hojadevida');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_dispo_codigo = thisOr($_REQUEST['filterer_dispo_codigo'], '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: dispo_codigo
	$combo_dispo_codigo = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='hojadevida' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='hojadevida' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `hojadevida` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'hojadevida_view.php', false);
		}
		$combo_dispo_codigo->SelectedData = $row['dispo_codigo'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_dispo_codigo->SelectedData = $filterer_dispo_codigo;
	}
	$combo_dispo_codigo->HTML = '<span id="dispo_codigo-container' . $rnd1 . '"></span><input type="hidden" name="dispo_codigo" id="dispo_codigo' . $rnd1 . '" value="' . html_attr($combo_dispo_codigo->SelectedData) . '">';
	$combo_dispo_codigo->MatchText = '<span id="dispo_codigo-container-readonly' . $rnd1 . '"></span><input type="hidden" name="dispo_codigo" id="dispo_codigo' . $rnd1 . '" value="' . html_attr($combo_dispo_codigo->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_dispo_codigo__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['dispo_codigo'] : htmlspecialchars($filterer_dispo_codigo, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(dispo_codigo_reload__RAND__) == 'function') dispo_codigo_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function dispo_codigo_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#dispo_codigo-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_dispo_codigo__RAND__.value, t: 'hojadevida', f: 'dispo_codigo' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="dispo_codigo"]').val(resp.results[0].id);
							$j('[id=dispo_codigo-container-readonly__RAND__]').html('<span id="dispo_codigo-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=dispositivos_view_parent]').hide(); } else { $j('.btn[id=dispositivos_view_parent]').show(); }


							if(typeof(dispo_codigo_update_autofills__RAND__) == 'function') dispo_codigo_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'hojadevida', f: 'dispo_codigo' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_dispo_codigo__RAND__.value = e.added.id;
				AppGini.current_dispo_codigo__RAND__.text = e.added.text;
				$j('[name="dispo_codigo"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=dispositivos_view_parent]').hide(); } else { $j('.btn[id=dispositivos_view_parent]').show(); }


				if(typeof(dispo_codigo_update_autofills__RAND__) == 'function') dispo_codigo_update_autofills__RAND__();
			});

			if(!$j("#dispo_codigo-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_dispo_codigo__RAND__.value, t: 'hojadevida', f: 'dispo_codigo' },
					success: function(resp) {
						$j('[name="dispo_codigo"]').val(resp.results[0].id);
						$j('[id=dispo_codigo-container-readonly__RAND__]').html('<span id="dispo_codigo-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=dispositivos_view_parent]').hide(); } else { $j('.btn[id=dispositivos_view_parent]').show(); }

						if(typeof(dispo_codigo_update_autofills__RAND__) == 'function') dispo_codigo_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_dispo_codigo__RAND__.value, t: 'hojadevida', f: 'dispo_codigo' },
				success: function(resp) {
					$j('[id=dispo_codigo-container__RAND__], [id=dispo_codigo-container-readonly__RAND__]').html('<span id="dispo_codigo-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=dispositivos_view_parent]').hide(); } else { $j('.btn[id=dispositivos_view_parent]').show(); }

					if(typeof(dispo_codigo_update_autofills__RAND__) == 'function') dispo_codigo_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/hojadevida_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/hojadevida_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalles Ficha Tecnica', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return hojadevida_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return hojadevida_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return hojadevida_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#dispo_codigo').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#dispo_codigo_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#hardware').replaceWith('<div class=\"form-control-static\" id=\"hardware\">' + (jQuery('#hardware').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#carga').replaceWith('<div class=\"form-control-static\" id=\"carga\">' + (jQuery('#carga').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#carga, #carga-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(dispo_codigo)%%>', $combo_dispo_codigo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(dispo_codigo)%%>', $combo_dispo_codigo->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(dispo_codigo)%%>', urlencode($combo_dispo_codigo->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('dispo_codigo' => array('dispositivos', 'Codigo'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(dispo_codigo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hardware)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(software)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(carga)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="carga" id="carga" data-filetypes="doc|docx|pdf|jpg|jpge|bpm|png" data-maxsize="5120000" accept=".doc,.docx,.pdf,.jpg,.jpge,.bpm,.png">'), $templateCode);
	if($AllowUpdate && $row['carga'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(carga)%%>', '<br><input type="checkbox" name="carga_remove" id="carga_remove" value="1"> <label for="carga_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(carga)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(creado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(creado_por)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(editado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(editado_por)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(dispo_codigo)%%>', safe_html($urow['dispo_codigo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(dispo_codigo)%%>', html_attr($row['dispo_codigo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(dispo_codigo)%%>', urlencode($urow['dispo_codigo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hardware)%%>', safe_html($urow['hardware']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hardware)%%>', html_attr($row['hardware']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hardware)%%>', urlencode($urow['hardware']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(software)%%>', '<textarea name="software" id="software" rows="5">' . html_attr($row['software']) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(software)%%>', '<div id="software" class="form-control-static">' . $row['software'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(software)%%>', nl2br($row['software']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(software)%%>', urlencode($urow['software']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(carga)%%>', safe_html($urow['carga']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(carga)%%>', html_attr($row['carga']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(carga)%%>', urlencode($urow['carga']), $templateCode);
		$templateCode = str_replace('<%%VALUE(creado)%%>', app_datetime($row['creado'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creado)%%>', urlencode(app_datetime($urow['creado'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(creado_por)%%>', safe_html($urow['creado_por']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creado_por)%%>', urlencode($urow['creado_por']), $templateCode);
		$templateCode = str_replace('<%%VALUE(editado)%%>', app_datetime($row['editado'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(editado)%%>', urlencode(app_datetime($urow['editado'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(editado_por)%%>', safe_html($urow['editado_por']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(editado_por)%%>', urlencode($urow['editado_por']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(dispo_codigo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(dispo_codigo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hardware)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hardware)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(software)%%>', '<textarea name="software" id="software" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(carga)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(carga)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(creado)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creado)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(creado_por)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(creado_por)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(editado)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(editado)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(editado_por)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(editado_por)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('cargaEdit')) { document.getElementById('cargaEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('cargaEditLink')) { document.getElementById('cargaEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tdispo_codigo_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'hojadevida_autofill.php?rnd1=$rnd1&mfk=dispo_codigo&id=' + encodeURIComponent('".addslashes($row['dispo_codigo'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'hojadevida_autofill.php?rnd1=$rnd1&mfk=dispo_codigo&id=' + encodeURIComponent(AppGini.current_dispo_codigo{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#dispo_codigo$rnd1').prop('disabled', true); \$j('#dispo_codigoLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#dispo_codigo$rnd1').prop('disabled', false); " : "\$j('#dispo_codigo$rnd1').prop('disabled', true); ")."\$j('#dispo_codigoLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#dispo_codigo_caption').length) \$j('#dispo_codigo_caption').click(function() { dispo_codigo_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('hojadevida');
	if($selected_id) {
		$jdata = get_joined_record('hojadevida', $selected_id);
		if($jdata === false) $jdata = get_defaults('hojadevida');
		$rdata = $row;
	}
	$templateCode .= loadView('hojadevida-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: hojadevida_dv
	if(function_exists('hojadevida_dv')) {
		$args=[];
		hojadevida_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}