<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('movi_recepcion_articulos');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'destino':
			if(!$id) {
				?>
				$j('#o_direccion<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#ciudad<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `unidades`.`id_unidades` as 'id_unidades', `unidades`.`nombre` as 'nombre', `unidades`.`abreviado` as 'abreviado', IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') as 'ciudad', `unidades`.`telefono` as 'telefono', `unidades`.`direccion` as 'direccion', `unidades`.`ubicacion` as 'ubicacion', IF(    CHAR_LENGTH(`prestador1`.`nombre`) || CHAR_LENGTH(`prestador1`.`nit`), CONCAT_WS('',   `prestador1`.`nombre`, ' | ', `prestador1`.`nit`), '') as 'prestador', `unidades`.`logo` as 'logo', `unidades`.`dispositivos_costo` as 'dispositivos_costo', `unidades`.`mobiliario_costo` as 'mobiliario_costo', `unidades`.`costo_total` as 'costo_total' FROM `unidades` LEFT JOIN `ciudades` as ciudades1 ON `ciudades1`.`id_ciudad`=`unidades`.`ciudad` LEFT JOIN `prestador` as prestador1 ON `prestador1`.`id`=`unidades`.`prestador`  WHERE `unidades`.`id_unidades`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#o_direccion<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['direccion']))); ?>&nbsp;');
			$j('#ciudad<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['ciudad']))); ?>&nbsp;');
			<?php
			break;

		case 'nombre':
			if(!$id) {
				?>
				$j('#telefono<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `contactos`.`id_contactos` as 'id_contactos', IF(    CHAR_LENGTH(`contactos_tipo_contacto1`.`tipo_contacto`), CONCAT_WS('',   `contactos_tipo_contacto1`.`tipo_contacto`), '') as 'tipo_contacto', IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`), '') as 'tipo_iden', `contactos`.`identificacion` as 'identificacion', `contactos`.`nombre` as 'nombre', IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') as 'ciudad', `contactos`.`telefono` as 'telefono', `contactos`.`direccion` as 'direccion', IF(    CHAR_LENGTH(`tipo_relacion1`.`tipo_relac`), CONCAT_WS('',   `tipo_relacion1`.`tipo_relac`), '') as 'tipo_relacion', `contactos`.`nota` as 'nota', if(`contactos`.`reg_creado`,date_format(`contactos`.`reg_creado`,'%d/%m/%Y %h:%i %p'),'') as 'reg_creado', if(`contactos`.`creado`,date_format(`contactos`.`creado`,'%d/%m/%Y %h:%i %p'),'') as 'creado', `contactos`.`creado_por` as 'creado_por', if(`contactos`.`editado`,date_format(`contactos`.`editado`,'%d/%m/%Y %h:%i %p'),'') as 'editado', `contactos`.`editado_por` as 'editado_por' FROM `contactos` LEFT JOIN `contactos_tipo_contacto` as contactos_tipo_contacto1 ON `contactos_tipo_contacto1`.`id_tipo_contacto`=`contactos`.`tipo_contacto` LEFT JOIN `tipo_iden` as tipo_iden1 ON `tipo_iden1`.`id_iden`=`contactos`.`tipo_iden` LEFT JOIN `ciudades` as ciudades1 ON `ciudades1`.`id_ciudad`=`contactos`.`ciudad` LEFT JOIN `tipo_relacion` as tipo_relacion1 ON `tipo_relacion1`.`id_tiporelac`=`contactos`.`tipo_relacion`  WHERE `contactos`.`id_contactos`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#telefono<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['telefono']))); ?>&nbsp;');
			<?php
			break;


	}

?>