<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/movi_envio_articulo.php");
	include_once("{$currDir}/movi_envio_articulo_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('movi_envio_articulo');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'movi_envio_articulo';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`movi_envio_articulo`.`id`" => "id",
		"IF(    CHAR_LENGTH(`movimientos_articulos1`.`id_movi`), CONCAT_WS('',   `movimientos_articulos1`.`id_movi`), '') /* Id movi */" => "id_movi",
		"if(`movi_envio_articulo`.`fecha_envio`,date_format(`movi_envio_articulo`.`fecha_envio`,'%d/%m/%Y'),'')" => "fecha_envio",
		"IF(    CHAR_LENGTH(`unidades1`.`nombre`), CONCAT_WS('',   `unidades1`.`nombre`), '') /* Origen */" => "origen",
		"IF(    CHAR_LENGTH(`unidades1`.`direccion`), CONCAT_WS('',   `unidades1`.`direccion`), '') /* Ubicacion */" => "ubicacion",
		"`movi_envio_articulo`.`destino`" => "destino",
		"`movi_envio_articulo`.`d_direccion`" => "d_direccion",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad destino */" => "ciudad",
		"IF(    CHAR_LENGTH(`contactos1`.`nombre`), CONCAT_WS('',   `contactos1`.`nombre`), '') /* Responsable de envio */" => "nombre",
		"IF(    CHAR_LENGTH(`contactos1`.`telefono`), CONCAT_WS('',   `contactos1`.`telefono`), '') /* Telefono */" => "telefono",
		"`movi_envio_articulo`.`detalles`" => "detalles",
		"if(`movi_envio_articulo`.`creado`,date_format(`movi_envio_articulo`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`movi_envio_articulo`.`creado_por`" => "creado_por",
		"if(`movi_envio_articulo`.`editado`,date_format(`movi_envio_articulo`.`editado`,'%d/%m/%Y %h:%i %p'),'')" => "editado",
		"`movi_envio_articulo`.`editado_por`" => "editado_por",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`movi_envio_articulo`.`id`',
		2 => '`movimientos_articulos1`.`id_movi`',
		3 => '`movi_envio_articulo`.`fecha_envio`',
		4 => '`unidades1`.`nombre`',
		5 => '`unidades1`.`direccion`',
		6 => 6,
		7 => 7,
		8 => '`ciudades1`.`ciudad`',
		9 => '`contactos1`.`nombre`',
		10 => '`contactos1`.`telefono`',
		11 => 11,
		12 => '`movi_envio_articulo`.`creado`',
		13 => 13,
		14 => '`movi_envio_articulo`.`editado`',
		15 => 15,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`movi_envio_articulo`.`id`" => "id",
		"IF(    CHAR_LENGTH(`movimientos_articulos1`.`id_movi`), CONCAT_WS('',   `movimientos_articulos1`.`id_movi`), '') /* Id movi */" => "id_movi",
		"if(`movi_envio_articulo`.`fecha_envio`,date_format(`movi_envio_articulo`.`fecha_envio`,'%d/%m/%Y'),'')" => "fecha_envio",
		"IF(    CHAR_LENGTH(`unidades1`.`nombre`), CONCAT_WS('',   `unidades1`.`nombre`), '') /* Origen */" => "origen",
		"IF(    CHAR_LENGTH(`unidades1`.`direccion`), CONCAT_WS('',   `unidades1`.`direccion`), '') /* Ubicacion */" => "ubicacion",
		"`movi_envio_articulo`.`destino`" => "destino",
		"`movi_envio_articulo`.`d_direccion`" => "d_direccion",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad destino */" => "ciudad",
		"IF(    CHAR_LENGTH(`contactos1`.`nombre`), CONCAT_WS('',   `contactos1`.`nombre`), '') /* Responsable de envio */" => "nombre",
		"IF(    CHAR_LENGTH(`contactos1`.`telefono`), CONCAT_WS('',   `contactos1`.`telefono`), '') /* Telefono */" => "telefono",
		"`movi_envio_articulo`.`detalles`" => "detalles",
		"if(`movi_envio_articulo`.`creado`,date_format(`movi_envio_articulo`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`movi_envio_articulo`.`creado_por`" => "creado_por",
		"if(`movi_envio_articulo`.`editado`,date_format(`movi_envio_articulo`.`editado`,'%d/%m/%Y %h:%i %p'),'')" => "editado",
		"`movi_envio_articulo`.`editado_por`" => "editado_por",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`movi_envio_articulo`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`movimientos_articulos1`.`id_movi`), CONCAT_WS('',   `movimientos_articulos1`.`id_movi`), '') /* Id movi */" => "Id movi",
		"`movi_envio_articulo`.`fecha_envio`" => "Fecha envio",
		"IF(    CHAR_LENGTH(`unidades1`.`nombre`), CONCAT_WS('',   `unidades1`.`nombre`), '') /* Origen */" => "Origen",
		"IF(    CHAR_LENGTH(`unidades1`.`direccion`), CONCAT_WS('',   `unidades1`.`direccion`), '') /* Ubicacion */" => "Ubicacion",
		"`movi_envio_articulo`.`destino`" => "Lugar de destino",
		"`movi_envio_articulo`.`d_direccion`" => "Direccion de el destino",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad destino */" => "Ciudad destino",
		"IF(    CHAR_LENGTH(`contactos1`.`nombre`), CONCAT_WS('',   `contactos1`.`nombre`), '') /* Responsable de envio */" => "Responsable de envio",
		"IF(    CHAR_LENGTH(`contactos1`.`telefono`), CONCAT_WS('',   `contactos1`.`telefono`), '') /* Telefono */" => "Telefono",
		"`movi_envio_articulo`.`detalles`" => "Detalles del envio",
		"`movi_envio_articulo`.`creado`" => "Creado",
		"`movi_envio_articulo`.`creado_por`" => "Creado por",
		"`movi_envio_articulo`.`editado`" => "Editado",
		"`movi_envio_articulo`.`editado_por`" => "Editado por",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`movi_envio_articulo`.`id`" => "id",
		"IF(    CHAR_LENGTH(`movimientos_articulos1`.`id_movi`), CONCAT_WS('',   `movimientos_articulos1`.`id_movi`), '') /* Id movi */" => "id_movi",
		"if(`movi_envio_articulo`.`fecha_envio`,date_format(`movi_envio_articulo`.`fecha_envio`,'%d/%m/%Y'),'')" => "fecha_envio",
		"IF(    CHAR_LENGTH(`unidades1`.`nombre`), CONCAT_WS('',   `unidades1`.`nombre`), '') /* Origen */" => "origen",
		"IF(    CHAR_LENGTH(`unidades1`.`direccion`), CONCAT_WS('',   `unidades1`.`direccion`), '') /* Ubicacion */" => "ubicacion",
		"`movi_envio_articulo`.`destino`" => "destino",
		"`movi_envio_articulo`.`d_direccion`" => "d_direccion",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad destino */" => "ciudad",
		"IF(    CHAR_LENGTH(`contactos1`.`nombre`), CONCAT_WS('',   `contactos1`.`nombre`), '') /* Responsable de envio */" => "nombre",
		"IF(    CHAR_LENGTH(`contactos1`.`telefono`), CONCAT_WS('',   `contactos1`.`telefono`), '') /* Telefono */" => "telefono",
		"`movi_envio_articulo`.`detalles`" => "detalles",
		"if(`movi_envio_articulo`.`creado`,date_format(`movi_envio_articulo`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`movi_envio_articulo`.`creado_por`" => "creado_por",
		"if(`movi_envio_articulo`.`editado`,date_format(`movi_envio_articulo`.`editado`,'%d/%m/%Y %h:%i %p'),'')" => "editado",
		"`movi_envio_articulo`.`editado_por`" => "editado_por",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['id_movi' => 'Id movi', 'origen' => 'Origen', 'ciudad' => 'Ciudad destino', 'nombre' => 'Responsable de envio', ];

	$x->QueryFrom = "`movi_envio_articulo` LEFT JOIN `movimientos_articulos` as movimientos_articulos1 ON `movimientos_articulos1`.`id_movi`=`movi_envio_articulo`.`id_movi` LEFT JOIN `unidades` as unidades1 ON `unidades1`.`id_unidades`=`movi_envio_articulo`.`origen` LEFT JOIN `ciudades` as ciudades1 ON `ciudades1`.`id_ciudad`=`movi_envio_articulo`.`ciudad` LEFT JOIN `contactos` as contactos1 ON `contactos1`.`id_contactos`=`movi_envio_articulo`.`nombre` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'movi_envio_articulo_view.php';
	$x->RedirectAfterInsert = 'movi_envio_articulo_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Envio';
	$x->TableIcon = 'resources/table_icons/arrow_right.png';
	$x->PrimaryKey = '`movi_envio_articulo`.`id`';
	$x->DefaultSortField = '`movi_envio_articulo`.`creado`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Fecha envio', 'Origen', 'Ubicacion', 'Lugar de destino', 'Direccion de el destino', 'Ciudad destino', 'Responsable de envio', 'Telefono', 'Detalles del envio', 'Creado', ];
	$x->ColFieldName = ['fecha_envio', 'origen', 'ubicacion', 'destino', 'd_direccion', 'ciudad', 'nombre', 'telefono', 'detalles', 'creado', ];
	$x->ColNumber  = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/movi_envio_articulo_templateTV.html';
	$x->SelectedTemplate = 'templates/movi_envio_articulo_templateTVS.html';
	$x->TemplateDV = 'templates/movi_envio_articulo_templateDV.html';
	$x->TemplateDVP = 'templates/movi_envio_articulo_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: movi_envio_articulo_init
	$render = true;
	if(function_exists('movi_envio_articulo_init')) {
		$args = [];
		$render = movi_envio_articulo_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: movi_envio_articulo_header
	$headerCode = '';
	if(function_exists('movi_envio_articulo_header')) {
		$args = [];
		$headerCode = movi_envio_articulo_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: movi_envio_articulo_footer
	$footerCode = '';
	if(function_exists('movi_envio_articulo_footer')) {
		$args = [];
		$footerCode = movi_envio_articulo_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
