<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/perfil_familia.php");
	include_once("{$currDir}/perfil_familia_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('perfil_familia');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'perfil_familia';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`perfil_familia`.`id`" => "id",
		"IF(    CHAR_LENGTH(`perfil1`.`id`) || CHAR_LENGTH(`perfil1`.`apellidos`), CONCAT_WS('',   `perfil1`.`id`, ' ', `perfil1`.`apellidos`), '') /* Usuario */" => "id_perfil",
		"IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`) || CHAR_LENGTH(`perfil1`.`numero_id`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`, ' ', `perfil1`.`numero_id`), '') /* Identificacion */" => "identificacion",
		"IF(    CHAR_LENGTH(`tipo_parentesco1`.`parentesco`), CONCAT_WS('',   `tipo_parentesco1`.`parentesco`), '') /* Parentesco */" => "parentesco",
		"`perfil_familia`.`nombre`" => "nombre",
		"`perfil_familia`.`telefono`" => "telefono",
		"`perfil_familia`.`direccion`" => "direccion",
		"if(`perfil_familia`.`creado`,date_format(`perfil_familia`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`perfil_familia`.`creado_por`" => "creado_por",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`perfil_familia`.`id`',
		2 => 2,
		3 => 3,
		4 => '`tipo_parentesco1`.`parentesco`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`perfil_familia`.`creado`',
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`perfil_familia`.`id`" => "id",
		"IF(    CHAR_LENGTH(`perfil1`.`id`) || CHAR_LENGTH(`perfil1`.`apellidos`), CONCAT_WS('',   `perfil1`.`id`, ' ', `perfil1`.`apellidos`), '') /* Usuario */" => "id_perfil",
		"IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`) || CHAR_LENGTH(`perfil1`.`numero_id`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`, ' ', `perfil1`.`numero_id`), '') /* Identificacion */" => "identificacion",
		"IF(    CHAR_LENGTH(`tipo_parentesco1`.`parentesco`), CONCAT_WS('',   `tipo_parentesco1`.`parentesco`), '') /* Parentesco */" => "parentesco",
		"`perfil_familia`.`nombre`" => "nombre",
		"`perfil_familia`.`telefono`" => "telefono",
		"`perfil_familia`.`direccion`" => "direccion",
		"if(`perfil_familia`.`creado`,date_format(`perfil_familia`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`perfil_familia`.`creado_por`" => "creado_por",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`perfil_familia`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`perfil1`.`id`) || CHAR_LENGTH(`perfil1`.`apellidos`), CONCAT_WS('',   `perfil1`.`id`, ' ', `perfil1`.`apellidos`), '') /* Usuario */" => "Usuario",
		"IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`) || CHAR_LENGTH(`perfil1`.`numero_id`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`, ' ', `perfil1`.`numero_id`), '') /* Identificacion */" => "Identificacion",
		"IF(    CHAR_LENGTH(`tipo_parentesco1`.`parentesco`), CONCAT_WS('',   `tipo_parentesco1`.`parentesco`), '') /* Parentesco */" => "Parentesco",
		"`perfil_familia`.`nombre`" => "Nombre",
		"`perfil_familia`.`telefono`" => "Telefono",
		"`perfil_familia`.`direccion`" => "Direccion",
		"`perfil_familia`.`creado`" => "Creado",
		"`perfil_familia`.`creado_por`" => "Creado por",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`perfil_familia`.`id`" => "id",
		"IF(    CHAR_LENGTH(`perfil1`.`id`) || CHAR_LENGTH(`perfil1`.`apellidos`), CONCAT_WS('',   `perfil1`.`id`, ' ', `perfil1`.`apellidos`), '') /* Usuario */" => "id_perfil",
		"IF(    CHAR_LENGTH(`tipo_iden1`.`tipo_iden_abre`) || CHAR_LENGTH(`perfil1`.`numero_id`), CONCAT_WS('',   `tipo_iden1`.`tipo_iden_abre`, ' ', `perfil1`.`numero_id`), '') /* Identificacion */" => "identificacion",
		"IF(    CHAR_LENGTH(`tipo_parentesco1`.`parentesco`), CONCAT_WS('',   `tipo_parentesco1`.`parentesco`), '') /* Parentesco */" => "parentesco",
		"`perfil_familia`.`nombre`" => "nombre",
		"`perfil_familia`.`telefono`" => "telefono",
		"`perfil_familia`.`direccion`" => "direccion",
		"if(`perfil_familia`.`creado`,date_format(`perfil_familia`.`creado`,'%d/%m/%Y %h:%i %p'),'')" => "creado",
		"`perfil_familia`.`creado_por`" => "creado_por",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['id_perfil' => 'Usuario', 'parentesco' => 'Parentesco', ];

	$x->QueryFrom = "`perfil_familia` LEFT JOIN `perfil` as perfil1 ON `perfil1`.`id`=`perfil_familia`.`id_perfil` LEFT JOIN `tipo_parentesco` as tipo_parentesco1 ON `tipo_parentesco1`.`id`=`perfil_familia`.`parentesco` LEFT JOIN `tipo_iden` as tipo_iden1 ON `tipo_iden1`.`id_iden`=`perfil1`.`tipo_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'perfil_familia_view.php';
	$x->RedirectAfterInsert = 'perfil_familia_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Familia';
	$x->TableIcon = 'resources/table_icons/client_account_template.png';
	$x->PrimaryKey = '`perfil_familia`.`id`';
	$x->DefaultSortField = '`perfil_familia`.`creado`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Usuario', 'Identificacion', 'Parentesco', 'Nombre', 'Telefono', 'Direccion', ];
	$x->ColFieldName = ['id_perfil', 'identificacion', 'parentesco', 'nombre', 'telefono', 'direccion', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/perfil_familia_templateTV.html';
	$x->SelectedTemplate = 'templates/perfil_familia_templateTVS.html';
	$x->TemplateDV = 'templates/perfil_familia_templateDV.html';
	$x->TemplateDVP = 'templates/perfil_familia_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: perfil_familia_init
	$render = true;
	if(function_exists('perfil_familia_init')) {
		$args = [];
		$render = perfil_familia_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: perfil_familia_header
	$headerCode = '';
	if(function_exists('perfil_familia_header')) {
		$args = [];
		$headerCode = perfil_familia_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: perfil_familia_footer
	$footerCode = '';
	if(function_exists('perfil_familia_footer')) {
		$args = [];
		$footerCode = perfil_familia_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
