<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/tipo_documento.php");
	include_once("{$currDir}/tipo_documento_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('tipo_documento');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tipo_documento';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tipo_documento`.`id_tipodoc`" => "id_tipodoc",
		"`tipo_documento`.`tipo_doc`" => "tipo_doc",
		"IF(    CHAR_LENGTH(`tipo_document_grupo1`.`grupo`), CONCAT_WS('',   `tipo_document_grupo1`.`grupo`), '') /* Grupo */" => "grupo",
		"`tipo_documento`.`descripcion`" => "descripcion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tipo_documento`.`id_tipodoc`',
		2 => 2,
		3 => '`tipo_document_grupo1`.`grupo`',
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tipo_documento`.`id_tipodoc`" => "id_tipodoc",
		"`tipo_documento`.`tipo_doc`" => "tipo_doc",
		"IF(    CHAR_LENGTH(`tipo_document_grupo1`.`grupo`), CONCAT_WS('',   `tipo_document_grupo1`.`grupo`), '') /* Grupo */" => "grupo",
		"`tipo_documento`.`descripcion`" => "descripcion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tipo_documento`.`id_tipodoc`" => "ID",
		"`tipo_documento`.`tipo_doc`" => "Tipo de documento",
		"IF(    CHAR_LENGTH(`tipo_document_grupo1`.`grupo`), CONCAT_WS('',   `tipo_document_grupo1`.`grupo`), '') /* Grupo */" => "Grupo",
		"`tipo_documento`.`descripcion`" => "Descripcion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tipo_documento`.`id_tipodoc`" => "id_tipodoc",
		"`tipo_documento`.`tipo_doc`" => "tipo_doc",
		"IF(    CHAR_LENGTH(`tipo_document_grupo1`.`grupo`), CONCAT_WS('',   `tipo_document_grupo1`.`grupo`), '') /* Grupo */" => "grupo",
		"`tipo_documento`.`descripcion`" => "descripcion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['grupo' => 'Grupo', ];

	$x->QueryFrom = "`tipo_documento` LEFT JOIN `tipo_document_grupo` as tipo_document_grupo1 ON `tipo_document_grupo1`.`id`=`tipo_documento`.`grupo` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = (getLoggedAdmin() !== false);
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tipo_documento_view.php';
	$x->RedirectAfterInsert = 'tipo_documento_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Tipo de documento';
	$x->TableIcon = 'resources/table_icons/cog_add.png';
	$x->PrimaryKey = '`tipo_documento`.`id_tipodoc`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Tipo de documento', 'Grupo', 'Descripcion', ];
	$x->ColFieldName = ['tipo_doc', 'grupo', 'descripcion', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tipo_documento_templateTV.html';
	$x->SelectedTemplate = 'templates/tipo_documento_templateTVS.html';
	$x->TemplateDV = 'templates/tipo_documento_templateDV.html';
	$x->TemplateDVP = 'templates/tipo_documento_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tipo_documento_init
	$render = true;
	if(function_exists('tipo_documento_init')) {
		$args = [];
		$render = tipo_documento_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tipo_documento_header
	$headerCode = '';
	if(function_exists('tipo_documento_header')) {
		$args = [];
		$headerCode = tipo_documento_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tipo_documento_footer
	$footerCode = '';
	if(function_exists('tipo_documento_footer')) {
		$args = [];
		$footerCode = tipo_documento_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
