<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/tipo_dispositivo.php");
	include_once("{$currDir}/tipo_dispositivo_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('tipo_dispositivo');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'tipo_dispositivo';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`tipo_dispositivo`.`id_tipodispo`" => "id_tipodispo",
		"`tipo_dispositivo`.`tipo_dispositivo`" => "tipo_dispositivo",
		"IF(    CHAR_LENGTH(`dispositivo_tipo_grupo1`.`grupo`), CONCAT_WS('',   `dispositivo_tipo_grupo1`.`grupo`), '') /* Grupo */" => "grupo_dispo",
		"`tipo_dispositivo`.`prefijo`" => "prefijo",
		"`tipo_dispositivo`.`descripcion`" => "descripcion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`tipo_dispositivo`.`id_tipodispo`',
		2 => 2,
		3 => '`dispositivo_tipo_grupo1`.`grupo`',
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`tipo_dispositivo`.`id_tipodispo`" => "id_tipodispo",
		"`tipo_dispositivo`.`tipo_dispositivo`" => "tipo_dispositivo",
		"IF(    CHAR_LENGTH(`dispositivo_tipo_grupo1`.`grupo`), CONCAT_WS('',   `dispositivo_tipo_grupo1`.`grupo`), '') /* Grupo */" => "grupo_dispo",
		"`tipo_dispositivo`.`prefijo`" => "prefijo",
		"`tipo_dispositivo`.`descripcion`" => "descripcion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`tipo_dispositivo`.`id_tipodispo`" => "ID",
		"`tipo_dispositivo`.`tipo_dispositivo`" => "Tipo de dispositivo",
		"IF(    CHAR_LENGTH(`dispositivo_tipo_grupo1`.`grupo`), CONCAT_WS('',   `dispositivo_tipo_grupo1`.`grupo`), '') /* Grupo */" => "Grupo",
		"`tipo_dispositivo`.`prefijo`" => "Prefijo",
		"`tipo_dispositivo`.`descripcion`" => "Descripcion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`tipo_dispositivo`.`id_tipodispo`" => "id_tipodispo",
		"`tipo_dispositivo`.`tipo_dispositivo`" => "tipo_dispositivo",
		"IF(    CHAR_LENGTH(`dispositivo_tipo_grupo1`.`grupo`), CONCAT_WS('',   `dispositivo_tipo_grupo1`.`grupo`), '') /* Grupo */" => "grupo_dispo",
		"`tipo_dispositivo`.`prefijo`" => "prefijo",
		"`tipo_dispositivo`.`descripcion`" => "descripcion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['grupo_dispo' => 'Grupo', ];

	$x->QueryFrom = "`tipo_dispositivo` LEFT JOIN `dispositivo_tipo_grupo` as dispositivo_tipo_grupo1 ON `dispositivo_tipo_grupo1`.`id`=`tipo_dispositivo`.`grupo_dispo` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = (getLoggedAdmin() !== false);
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'tipo_dispositivo_view.php';
	$x->RedirectAfterInsert = 'tipo_dispositivo_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Tipo de dispositivo';
	$x->TableIcon = 'resources/table_icons/cog_add.png';
	$x->PrimaryKey = '`tipo_dispositivo`.`id_tipodispo`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Tipo de dispositivo', 'Grupo', 'Prefijo', 'Descripcion', ];
	$x->ColFieldName = ['tipo_dispositivo', 'grupo_dispo', 'prefijo', 'descripcion', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/tipo_dispositivo_templateTV.html';
	$x->SelectedTemplate = 'templates/tipo_dispositivo_templateTVS.html';
	$x->TemplateDV = 'templates/tipo_dispositivo_templateDV.html';
	$x->TemplateDVP = 'templates/tipo_dispositivo_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: tipo_dispositivo_init
	$render = true;
	if(function_exists('tipo_dispositivo_init')) {
		$args = [];
		$render = tipo_dispositivo_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tipo_dispositivo_header
	$headerCode = '';
	if(function_exists('tipo_dispositivo_header')) {
		$args = [];
		$headerCode = tipo_dispositivo_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: tipo_dispositivo_footer
	$footerCode = '';
	if(function_exists('tipo_dispositivo_footer')) {
		$args = [];
		$footerCode = tipo_dispositivo_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
