<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/unidades.php");
	include_once("{$currDir}/unidades_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('unidades');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'unidades';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`unidades`.`id_unidades`" => "id_unidades",
		"`unidades`.`nombre`" => "nombre",
		"`unidades`.`abreviado`" => "abreviado",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"`unidades`.`telefono`" => "telefono",
		"`unidades`.`direccion`" => "direccion",
		"`unidades`.`ubicacion`" => "ubicacion",
		"IF(    CHAR_LENGTH(`prestador1`.`nombre`) || CHAR_LENGTH(`prestador1`.`nit`), CONCAT_WS('',   `prestador1`.`nombre`, ' | ', `prestador1`.`nit`), '') /* Prestador */" => "prestador",
		"`unidades`.`logo`" => "logo",
		"`unidades`.`dispositivos_costo`" => "dispositivos_costo",
		"`unidades`.`mobiliario_costo`" => "mobiliario_costo",
		"`unidades`.`costo_total`" => "costo_total",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`unidades`.`id_unidades`',
		2 => 2,
		3 => 3,
		4 => '`ciudades1`.`ciudad`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => '`unidades`.`dispositivos_costo`',
		11 => '`unidades`.`mobiliario_costo`',
		12 => '`unidades`.`costo_total`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`unidades`.`id_unidades`" => "id_unidades",
		"`unidades`.`nombre`" => "nombre",
		"`unidades`.`abreviado`" => "abreviado",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"`unidades`.`telefono`" => "telefono",
		"`unidades`.`direccion`" => "direccion",
		"`unidades`.`ubicacion`" => "ubicacion",
		"IF(    CHAR_LENGTH(`prestador1`.`nombre`) || CHAR_LENGTH(`prestador1`.`nit`), CONCAT_WS('',   `prestador1`.`nombre`, ' | ', `prestador1`.`nit`), '') /* Prestador */" => "prestador",
		"`unidades`.`logo`" => "logo",
		"`unidades`.`dispositivos_costo`" => "dispositivos_costo",
		"`unidades`.`mobiliario_costo`" => "mobiliario_costo",
		"`unidades`.`costo_total`" => "costo_total",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`unidades`.`id_unidades`" => "ID",
		"`unidades`.`nombre`" => "Nombre de la unidad",
		"`unidades`.`abreviado`" => "Abreviado",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "Ciudad",
		"`unidades`.`telefono`" => "Telefono",
		"`unidades`.`direccion`" => "Direccion",
		"`unidades`.`ubicacion`" => "Ubicacion",
		"IF(    CHAR_LENGTH(`prestador1`.`nombre`) || CHAR_LENGTH(`prestador1`.`nit`), CONCAT_WS('',   `prestador1`.`nombre`, ' | ', `prestador1`.`nit`), '') /* Prestador */" => "Prestador",
		"`unidades`.`dispositivos_costo`" => "Costo de Dispositivos",
		"`unidades`.`mobiliario_costo`" => "Costo de Mobiliario",
		"`unidades`.`costo_total`" => "Costo total",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`unidades`.`id_unidades`" => "id_unidades",
		"`unidades`.`nombre`" => "nombre",
		"`unidades`.`abreviado`" => "abreviado",
		"IF(    CHAR_LENGTH(`ciudades1`.`ciudad`), CONCAT_WS('',   `ciudades1`.`ciudad`), '') /* Ciudad */" => "ciudad",
		"`unidades`.`telefono`" => "telefono",
		"`unidades`.`direccion`" => "direccion",
		"`unidades`.`ubicacion`" => "ubicacion",
		"IF(    CHAR_LENGTH(`prestador1`.`nombre`) || CHAR_LENGTH(`prestador1`.`nit`), CONCAT_WS('',   `prestador1`.`nombre`, ' | ', `prestador1`.`nit`), '') /* Prestador */" => "prestador",
		"`unidades`.`dispositivos_costo`" => "dispositivos_costo",
		"`unidades`.`mobiliario_costo`" => "mobiliario_costo",
		"`unidades`.`costo_total`" => "costo_total",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['ciudad' => 'Ciudad', 'prestador' => 'Prestador', ];

	$x->QueryFrom = "`unidades` LEFT JOIN `ciudades` as ciudades1 ON `ciudades1`.`id_ciudad`=`unidades`.`ciudad` LEFT JOIN `prestador` as prestador1 ON `prestador1`.`id`=`unidades`.`prestador` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'unidades_view.php';
	$x->RedirectAfterInsert = 'unidades_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Unidades Medicas';
	$x->TableIcon = 'resources/table_icons/building_add.png';
	$x->PrimaryKey = '`unidades`.`id_unidades`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Nombre de la unidad', 'Abreviado', 'Ciudad', 'Telefono', 'Direccion', 'Ubicacion', 'Prestador', 'Logo', 'Costo de Dispositivos', 'Costo de Mobiliario', 'Costo total', ];
	$x->ColFieldName = ['nombre', 'abreviado', 'ciudad', 'telefono', 'direccion', 'ubicacion', 'prestador', 'logo', 'dispositivos_costo', 'mobiliario_costo', 'costo_total', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/unidades_templateTV.html';
	$x->SelectedTemplate = 'templates/unidades_templateTVS.html';
	$x->TemplateDV = 'templates/unidades_templateDV.html';
	$x->TemplateDVP = 'templates/unidades_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: unidades_init
	$render = true;
	if(function_exists('unidades_init')) {
		$args = [];
		$render = unidades_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: unidades_header
	$headerCode = '';
	if(function_exists('unidades_header')) {
		$args = [];
		$headerCode = unidades_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: unidades_footer
	$footerCode = '';
	if(function_exists('unidades_footer')) {
		$args = [];
		$footerCode = unidades_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
