<?php

// Data functions (insert, update, delete, form) for table verificacion_articulos

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function verificacion_articulos_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('verificacion_articulos');
	if(!$arrPerm['insert']) return false;

	$data = [
		'tipo_dispo' => Request::lookup('codigo'),
		'nombre' => Request::lookup('codigo'),
		'serial' => Request::lookup('codigo'),
		'ubicacion' => Request::lookup('ubicacion', ''),
		'abreviado' => Request::lookup('ubicacion'),
		'verificacion' => Request::checkBox('verificacion', ''),
		'comentario' => br2nl(Request::val('comentario', '')),
		'fecha_verifi' => parseCode('<%%creationDateTime%%>', true, true),
		'verifi_por' => parseCode('<%%creatorUsername%%>', true),
	];

	if($data['ubicacion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Ubicacion': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['verificacion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Verificado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: verificacion_articulos_before_insert
	if(function_exists('verificacion_articulos_before_insert')) {
		$args = [];
		if(!verificacion_articulos_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('verificacion_articulos', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	// automatic codigo if passed as filterer
	if($_REQUEST['filterer_codigo']) {
		sql("UPDATE `verificacion_articulos` SET `codigo`='" . makeSafe($_REQUEST['filterer_codigo']) . "' WHERE `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	update_calc_fields('verificacion_articulos', $recID, calculated_fields()['verificacion_articulos']);

	// hook: verificacion_articulos_after_insert
	if(function_exists('verificacion_articulos_after_insert')) {
		$res = sql("SELECT * FROM `verificacion_articulos` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!verificacion_articulos_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('verificacion_articulos', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) verificacion_articulos_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function verificacion_articulos_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function verificacion_articulos_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('verificacion_articulos', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: verificacion_articulos_before_delete
	if(function_exists('verificacion_articulos_before_delete')) {
		$args = [];
		if(!verificacion_articulos_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `verificacion_articulos` WHERE `id`='{$selected_id}'", $eo);

	// hook: verificacion_articulos_after_delete
	if(function_exists('verificacion_articulos_after_delete')) {
		$args = [];
		verificacion_articulos_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='verificacion_articulos' AND `pkValue`='{$selected_id}'", $eo);
}

function verificacion_articulos_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('verificacion_articulos', $selected_id, 'edit')) return false;

	$data = [
		'tipo_dispo' => Request::lookup('codigo'),
		'nombre' => Request::lookup('codigo'),
		'serial' => Request::lookup('codigo'),
		'ubicacion' => Request::lookup('ubicacion', ''),
		'abreviado' => Request::lookup('ubicacion'),
		'verificacion' => Request::checkBox('verificacion', ''),
		'comentario' => br2nl(Request::val('comentario', '')),
	];

	if($data['ubicacion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Ubicacion': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['verificacion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Verificado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('verificacion_articulos', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: verificacion_articulos_before_update
	if(function_exists('verificacion_articulos_before_update')) {
		$args = ['old_data' => $old_data];
		if(!verificacion_articulos_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'verificacion_articulos', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="verificacion_articulos_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('verificacion_articulos', $data['selectedID'], calculated_fields()['verificacion_articulos']);

	// hook: verificacion_articulos_after_update
	if(function_exists('verificacion_articulos_after_update')) {
		$res = sql("SELECT * FROM `verificacion_articulos` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!verificacion_articulos_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='verificacion_articulos' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function verificacion_articulos_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('verificacion_articulos');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_codigo = thisOr($_REQUEST['filterer_codigo'], '');
	$filterer_ubicacion = thisOr($_REQUEST['filterer_ubicacion'], '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: codigo
	$combo_codigo = new DataCombo;
	// combobox: ubicacion
	$combo_ubicacion = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='verificacion_articulos' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='verificacion_articulos' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `verificacion_articulos` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'verificacion_articulos_view.php', false);
		}
		$combo_codigo->SelectedData = $row['codigo'];
		$combo_ubicacion->SelectedData = $row['ubicacion'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_codigo->SelectedData = $filterer_codigo;
		$combo_ubicacion->SelectedData = $filterer_ubicacion;
	}
	$combo_codigo->HTML = '<span id="codigo-container' . $rnd1 . '"></span><input type="hidden" name="codigo" id="codigo' . $rnd1 . '" value="' . html_attr($combo_codigo->SelectedData) . '">';
	$combo_codigo->MatchText = '<span id="codigo-container-readonly' . $rnd1 . '"></span><input type="hidden" name="codigo" id="codigo' . $rnd1 . '" value="' . html_attr($combo_codigo->SelectedData) . '">';
	$combo_ubicacion->HTML = '<span id="ubicacion-container' . $rnd1 . '"></span><input type="hidden" name="ubicacion" id="ubicacion' . $rnd1 . '" value="' . html_attr($combo_ubicacion->SelectedData) . '">';
	$combo_ubicacion->MatchText = '<span id="ubicacion-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ubicacion" id="ubicacion' . $rnd1 . '" value="' . html_attr($combo_ubicacion->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_codigo__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['codigo'] : htmlspecialchars($filterer_codigo, ENT_QUOTES)); ?>"};
		AppGini.current_ubicacion__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ubicacion'] : htmlspecialchars($filterer_ubicacion, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(codigo_reload__RAND__) == 'function') codigo_reload__RAND__();
				if(typeof(ubicacion_reload__RAND__) == 'function') ubicacion_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function codigo_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#codigo-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_codigo__RAND__.value, t: 'verificacion_articulos', f: 'codigo' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="codigo"]').val(resp.results[0].id);
							$j('[id=codigo-container-readonly__RAND__]').html('<span id="codigo-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=articulos_view_parent]').hide(); } else { $j('.btn[id=articulos_view_parent]').show(); }


							if(typeof(codigo_update_autofills__RAND__) == 'function') codigo_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'verificacion_articulos', f: 'codigo' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_codigo__RAND__.value = e.added.id;
				AppGini.current_codigo__RAND__.text = e.added.text;
				$j('[name="codigo"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=articulos_view_parent]').hide(); } else { $j('.btn[id=articulos_view_parent]').show(); }


				if(typeof(codigo_update_autofills__RAND__) == 'function') codigo_update_autofills__RAND__();
			});

			if(!$j("#codigo-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_codigo__RAND__.value, t: 'verificacion_articulos', f: 'codigo' },
					success: function(resp) {
						$j('[name="codigo"]').val(resp.results[0].id);
						$j('[id=codigo-container-readonly__RAND__]').html('<span id="codigo-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=articulos_view_parent]').hide(); } else { $j('.btn[id=articulos_view_parent]').show(); }

						if(typeof(codigo_update_autofills__RAND__) == 'function') codigo_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_codigo__RAND__.value, t: 'verificacion_articulos', f: 'codigo' },
				success: function(resp) {
					$j('[id=codigo-container__RAND__], [id=codigo-container-readonly__RAND__]').html('<span id="codigo-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=articulos_view_parent]').hide(); } else { $j('.btn[id=articulos_view_parent]').show(); }

					if(typeof(codigo_update_autofills__RAND__) == 'function') codigo_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function ubicacion_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#ubicacion-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_ubicacion__RAND__.value, t: 'verificacion_articulos', f: 'ubicacion' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="ubicacion"]').val(resp.results[0].id);
							$j('[id=ubicacion-container-readonly__RAND__]').html('<span id="ubicacion-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=unidades_view_parent]').hide(); } else { $j('.btn[id=unidades_view_parent]').show(); }


							if(typeof(ubicacion_update_autofills__RAND__) == 'function') ubicacion_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'verificacion_articulos', f: 'ubicacion' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_ubicacion__RAND__.value = e.added.id;
				AppGini.current_ubicacion__RAND__.text = e.added.text;
				$j('[name="ubicacion"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=unidades_view_parent]').hide(); } else { $j('.btn[id=unidades_view_parent]').show(); }


				if(typeof(ubicacion_update_autofills__RAND__) == 'function') ubicacion_update_autofills__RAND__();
			});

			if(!$j("#ubicacion-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_ubicacion__RAND__.value, t: 'verificacion_articulos', f: 'ubicacion' },
					success: function(resp) {
						$j('[name="ubicacion"]').val(resp.results[0].id);
						$j('[id=ubicacion-container-readonly__RAND__]').html('<span id="ubicacion-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=unidades_view_parent]').hide(); } else { $j('.btn[id=unidades_view_parent]').show(); }

						if(typeof(ubicacion_update_autofills__RAND__) == 'function') ubicacion_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_ubicacion__RAND__.value, t: 'verificacion_articulos', f: 'ubicacion' },
				success: function(resp) {
					$j('[id=ubicacion-container__RAND__], [id=ubicacion-container-readonly__RAND__]').html('<span id="ubicacion-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=unidades_view_parent]').hide(); } else { $j('.btn[id=unidades_view_parent]').show(); }

					if(typeof(ubicacion_update_autofills__RAND__) == 'function') ubicacion_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/verificacion_articulos_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/verificacion_articulos_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Verificacion Detalles', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return verificacion_articulos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return verificacion_articulos_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return verificacion_articulos_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#ubicacion').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ubicacion_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#verificacion').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#comentario').replaceWith('<div class=\"form-control-static\" id=\"comentario\">' + (jQuery('#comentario').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(codigo)%%>', $combo_codigo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(codigo)%%>', $combo_codigo->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(codigo)%%>', urlencode($combo_codigo->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(ubicacion)%%>', $combo_ubicacion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ubicacion)%%>', $combo_ubicacion->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(ubicacion)%%>', urlencode($combo_ubicacion->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('codigo' => array('articulos', 'Codigo'), 'ubicacion' => array('unidades', 'Ubicacion'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(codigo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ubicacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(verificacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(comentario)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha_verifi)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(verifi_por)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(codigo)%%>', safe_html($urow['codigo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(codigo)%%>', urlencode($urow['codigo']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ubicacion)%%>', safe_html($urow['ubicacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ubicacion)%%>', html_attr($row['ubicacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ubicacion)%%>', urlencode($urow['ubicacion']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(verificacion)%%>', ($row['verificacion'] ? "checked" : ""), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(comentario)%%>', safe_html($urow['comentario']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(comentario)%%>', safe_html($urow['comentario'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(comentario)%%>', urlencode($urow['comentario']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_verifi)%%>', app_datetime($row['fecha_verifi'], 'dt'), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_verifi)%%>', urlencode(app_datetime($urow['fecha_verifi'], 'dt')), $templateCode);
		$templateCode = str_replace('<%%VALUE(verifi_por)%%>', safe_html($urow['verifi_por']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(verifi_por)%%>', urlencode($urow['verifi_por']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(codigo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(codigo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ubicacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ubicacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(verificacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(comentario)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comentario)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha_verifi)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha_verifi)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(verifi_por)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(verifi_por)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tcodigo_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'verificacion_articulos_autofill.php?rnd1=$rnd1&mfk=codigo&id=' + encodeURIComponent('".addslashes($row['codigo'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'verificacion_articulos_autofill.php?rnd1=$rnd1&mfk=codigo&id=' + encodeURIComponent(AppGini.current_codigo{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#codigo$rnd1').prop('disabled', true); \$j('#codigoLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#codigo$rnd1').prop('disabled', false); " : "\$j('#codigo$rnd1').prop('disabled', true); ")."\$j('#codigoLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#codigo_caption').length) \$j('#codigo_caption').click(function() { codigo_update_autofills$rnd1(); });\n";

	$templateCode .= "\tubicacion_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'verificacion_articulos_autofill.php?rnd1=$rnd1&mfk=ubicacion&id=' + encodeURIComponent('".addslashes($row['ubicacion'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'verificacion_articulos_autofill.php?rnd1=$rnd1&mfk=ubicacion&id=' + encodeURIComponent(AppGini.current_ubicacion{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#ubicacion$rnd1').prop('disabled', true); \$j('#ubicacionLoading').html('<img src=loading.gif align=top>'); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#ubicacion$rnd1').prop('disabled', false); " : "\$j('#ubicacion$rnd1').prop('disabled', true); ")."\$j('#ubicacionLoading').html(''); \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#ubicacion_caption').length) \$j('#ubicacion_caption').click(function() { ubicacion_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	if( $_REQUEST['FilterField'][1]=='2' && $_REQUEST['FilterOperator'][1]=='<=>') {
		$templateCode.="\n<input type=hidden name=codigo value=\"" . html_attr($_REQUEST['FilterValue'][1]) . "\">\n";
	}

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('verificacion_articulos');
	if($selected_id) {
		$jdata = get_joined_record('verificacion_articulos', $selected_id);
		if($jdata === false) $jdata = get_defaults('verificacion_articulos');
		$rdata = $row;
	}
	$templateCode .= loadView('verificacion_articulos-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: verificacion_articulos_dv
	if(function_exists('verificacion_articulos_dv')) {
		$args=[];
		verificacion_articulos_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}